import type { SiteLocale } from "./locales";

export type TagLabelMap = Record<SiteLocale, string>;

export type SiteTag = {
  value: string;
  emoji: string;
  labels: TagLabelMap;
};

export const SITE_TAGS: SiteTag[] = [
  {
    value: "other",
    emoji: "☝️",
    labels: {
      ru: "Другое",
      en: "Other",
      de: "Sonstiges",
      es: "Otro",
      tr: "Diğer",
      fr: "Autre",
      it: "Altro",
      "pt-br": "Outro",
      id: "Lainnya",
      pl: "Inne",
    },
  },
  {
    value: "news",
    emoji: "📰",
    labels: {
      ru: "Новости",
      en: "News",
      de: "Nachrichten",
      es: "Noticias",
      tr: "Haberler",
      fr: "Actualités",
      it: "Notizie",
      "pt-br": "Notícias",
      id: "Berita",
      pl: "Wiadomości",
    },
  },
  {
    value: "politics",
    emoji: "🏛️",
    labels: {
      ru: "Политика",
      en: "Politics",
      de: "Politik",
      es: "Política",
      tr: "Politika",
      fr: "Politique",
      it: "Politica",
      "pt-br": "Política",
      id: "Politik",
      pl: "Polityka",
    },
  },
  {
    value: "economy",
    emoji: "📈",
    labels: {
      ru: "Экономика",
      en: "Economy",
      de: "Wirtschaft",
      es: "Economía",
      tr: "Ekonomi",
      fr: "Économie",
      it: "Economia",
      "pt-br": "Economia",
      id: "Ekonomi",
      pl: "Gospodarka",
    },
  },
  {
    value: "business",
    emoji: "💼",
    labels: {
      ru: "Бизнес",
      en: "Business",
      de: "Business",
      es: "Negocios",
      tr: "İş Dünyası",
      fr: "Business",
      it: "Business",
      "pt-br": "Negócios",
      id: "Bisnis",
      pl: "Biznes",
    },
  },
  {
    value: "finance",
    emoji: "💰",
    labels: {
      ru: "Финансы",
      en: "Finance",
      de: "Finanzen",
      es: "Finanzas",
      tr: "Finans",
      fr: "Finance",
      it: "Finanza",
      "pt-br": "Finanças",
      id: "Keuangan",
      pl: "Finanse",
    },
  },
  {
    value: "crypto",
    emoji: "₿",
    labels: {
      ru: "Крипта",
      en: "Crypto",
      de: "Krypto",
      es: "Cripto",
      tr: "Kripto",
      fr: "Crypto",
      it: "Cripto",
      "pt-br": "Cripto",
      id: "Kripto",
      pl: "Krypto",
    },
  },
  {
    value: "technology",
    emoji: "💻",
    labels: {
      ru: "Технологии",
      en: "Technology",
      de: "Technologie",
      es: "Tecnología",
      tr: "Teknoloji",
      fr: "Technologie",
      it: "Tecnologia",
      "pt-br": "Tecnologia",
      id: "Teknologi",
      pl: "Technologia",
    },
  },
  {
    value: "ai",
    emoji: "🤖",
    labels: {
      ru: "AI",
      en: "AI",
      de: "KI",
      es: "IA",
      tr: "YZ",
      fr: "IA",
      it: "IA",
      "pt-br": "IA",
      id: "AI",
      pl: "AI",
    },
  },
  {
    value: "science",
    emoji: "🔬",
    labels: {
      ru: "Наука",
      en: "Science",
      de: "Wissenschaft",
      es: "Ciencia",
      tr: "Bilim",
      fr: "Science",
      it: "Scienza",
      "pt-br": "Ciência",
      id: "Sains",
      pl: "Nauka",
    },
  },
  {
    value: "space",
    emoji: "🚀",
    labels: {
      ru: "Космос",
      en: "Space",
      de: "Weltraum",
      es: "Espacio",
      tr: "Uzay",
      fr: "Espace",
      it: "Spazio",
      "pt-br": "Espaço",
      id: "Antariksa",
      pl: "Kosmos",
    },
  },
  {
    value: "education",
    emoji: "📚",
    labels: {
      ru: "Образование",
      en: "Education",
      de: "Bildung",
      es: "Educación",
      tr: "Eğitim",
      fr: "Éducation",
      it: "Istruzione",
      "pt-br": "Educação",
      id: "Pendidikan",
      pl: "Edukacja",
    },
  },
  {
    value: "history",
    emoji: "🏺",
    labels: {
      ru: "История",
      en: "History",
      de: "Geschichte",
      es: "Historia",
      tr: "Tarih",
      fr: "Histoire",
      it: "Storia",
      "pt-br": "História",
      id: "Sejarah",
      pl: "Historia",
    },
  },
  {
    value: "culture",
    emoji: "🎭",
    labels: {
      ru: "Культура",
      en: "Culture",
      de: "Kultur",
      es: "Cultura",
      tr: "Kültür",
      fr: "Culture",
      it: "Cultura",
      "pt-br": "Cultura",
      id: "Budaya",
      pl: "Kultura",
    },
  },
  {
    value: "books",
    emoji: "📖",
    labels: {
      ru: "Книги",
      en: "Books",
      de: "Bücher",
      es: "Libros",
      tr: "Kitaplar",
      fr: "Livres",
      it: "Libri",
      "pt-br": "Livros",
      id: "Buku",
      pl: "Książki",
    },
  },
  {
    value: "art",
    emoji: "🎨",
    labels: {
      ru: "Арт",
      en: "Art",
      de: "Kunst",
      es: "Arte",
      tr: "Sanat",
      fr: "Art",
      it: "Arte",
      "pt-br": "Arte",
      id: "Seni",
      pl: "Sztuka",
    },
  },
  {
    value: "design",
    emoji: "🧩",
    labels: {
      ru: "Дизайн",
      en: "Design",
      de: "Design",
      es: "Diseño",
      tr: "Tasarım",
      fr: "Design",
      it: "Design",
      "pt-br": "Design",
      id: "Desain",
      pl: "Design",
    },
  },
  {
    value: "photography",
    emoji: "📷",
    labels: {
      ru: "Фото",
      en: "Photography",
      de: "Fotografie",
      es: "Fotografía",
      tr: "Fotoğrafçılık",
      fr: "Photographie",
      it: "Fotografia",
      "pt-br": "Fotografia",
      id: "Fotografi",
      pl: "Fotografia",
    },
  },
  {
    value: "cinema",
    emoji: "🎬",
    labels: {
      ru: "Кино",
      en: "Cinema",
      de: "Kino",
      es: "Cine",
      tr: "Sinema",
      fr: "Cinéma",
      it: "Cinema",
      "pt-br": "Cinema",
      id: "Film",
      pl: "Kino",
    },
  },
  {
    value: "series",
    emoji: "📺",
    labels: {
      ru: "Сериалы",
      en: "Series",
      de: "Serien",
      es: "Series",
      tr: "Diziler",
      fr: "Séries",
      it: "Serie",
      "pt-br": "Séries",
      id: "Serial",
      pl: "Seriale",
    },
  },
  {
    value: "music",
    emoji: "🎵",
    labels: {
      ru: "Музыка",
      en: "Music",
      de: "Musik",
      es: "Música",
      tr: "Müzik",
      fr: "Musique",
      it: "Musica",
      "pt-br": "Música",
      id: "Musik",
      pl: "Muzyka",
    },
  },
  {
    value: "gaming",
    emoji: "🎮",
    labels: {
      ru: "Игры",
      en: "Gaming",
      de: "Gaming",
      es: "Juegos",
      tr: "Oyun",
      fr: "Jeux",
      it: "Giochi",
      "pt-br": "Jogos",
      id: "Game",
      pl: "Gry",
    },
  },
  {
    value: "memes",
    emoji: "😂",
    labels: {
      ru: "Мемы",
      en: "Memes",
      de: "Memes",
      es: "Memes",
      tr: "Memler",
      fr: "Mèmes",
      it: "Meme",
      "pt-br": "Memes",
      id: "Meme",
      pl: "Memy",
    },
  },
  {
    value: "humor",
    emoji: "🤣",
    labels: {
      ru: "Юмор",
      en: "Humor",
      de: "Humor",
      es: "Humor",
      tr: "Mizah",
      fr: "Humour",
      it: "Umorismo",
      "pt-br": "Humor",
      id: "Humor",
      pl: "Humor",
    },
  },
  {
    value: "sports",
    emoji: "⚽",
    labels: {
      ru: "Спорт",
      en: "Sports",
      de: "Sport",
      es: "Deportes",
      tr: "Spor",
      fr: "Sport",
      it: "Sport",
      "pt-br": "Esportes",
      id: "Olahraga",
      pl: "Sport",
    },
  },
  {
    value: "mma",
    emoji: "🥊",
    labels: {
      ru: "MMA",
      en: "MMA",
      de: "MMA",
      es: "MMA",
      tr: "MMA",
      fr: "MMA",
      it: "MMA",
      "pt-br": "MMA",
      id: "MMA",
      pl: "MMA",
    },
  },
  {
    value: "fitness",
    emoji: "🏋️",
    labels: {
      ru: "Фитнес",
      en: "Fitness",
      de: "Fitness",
      es: "Fitness",
      tr: "Fitness",
      fr: "Fitness",
      it: "Fitness",
      "pt-br": "Fitness",
      id: "Fitness",
      pl: "Fitness",
    },
  },
  {
    value: "health",
    emoji: "🩺",
    labels: {
      ru: "Здоровье",
      en: "Health",
      de: "Gesundheit",
      es: "Salud",
      tr: "Sağlık",
      fr: "Santé",
      it: "Salute",
      "pt-br": "Saúde",
      id: "Kesehatan",
      pl: "Zdrowie",
    },
  },
  {
    value: "travel",
    emoji: "🧳",
    labels: {
      ru: "Путешествия",
      en: "Travel",
      de: "Reisen",
      es: "Viajes",
      tr: "Seyahat",
      fr: "Voyage",
      it: "Viaggi",
      "pt-br": "Viagem",
      id: "Perjalanan",
      pl: "Podróże",
    },
  },
  {
    value: "food",
    emoji: "🍔",
    labels: {
      ru: "Еда",
      en: "Food",
      de: "Essen",
      es: "Comida",
      tr: "Yemek",
      fr: "Cuisine",
      it: "Cibo",
      "pt-br": "Comida",
      id: "Makanan",
      pl: "Jedzenie",
    },
  },
  {
    value: "psychology",
    emoji: "🧠",
    labels: {
      ru: "Психология",
      en: "Psychology",
      de: "Psychologie",
      es: "Psicología",
      tr: "Psikoloji",
      fr: "Psychologie",
      it: "Psicologia",
      "pt-br": "Psicologia",
      id: "Psikologi",
      pl: "Psychologia",
    },
  },
  {
    value: "relationships",
    emoji: "❤️",
    labels: {
      ru: "Отношения",
      en: "Relationships",
      de: "Beziehungen",
      es: "Relaciones",
      tr: "İlişkiler",
      fr: "Relations",
      it: "Relazioni",
      "pt-br": "Relacionamentos",
      id: "Hubungan",
      pl: "Relacje",
    },
  },
  {
    value: "parenting",
    emoji: "👶",
    labels: {
      ru: "Родительство",
      en: "Parenting",
      de: "Elternschaft",
      es: "Crianza",
      tr: "Ebeveynlik",
      fr: "Parentalité",
      it: "Genitorialità",
      "pt-br": "Parentalidade",
      id: "Pengasuhan",
      pl: "Rodzicielstwo",
    },
  },
  {
    value: "fashion",
    emoji: "👗",
    labels: {
      ru: "Мода",
      en: "Fashion",
      de: "Mode",
      es: "Moda",
      tr: "Moda",
      fr: "Mode",
      it: "Moda",
      "pt-br": "Moda",
      id: "Mode",
      pl: "Moda",
    },
  },
  {
    value: "beauty",
    emoji: "💄",
    labels: {
      ru: "Красота",
      en: "Beauty",
      de: "Beauty",
      es: "Belleza",
      tr: "Güzellik",
      fr: "Beauté",
      it: "Bellezza",
      "pt-br": "Beleza",
      id: "Kecantikan",
      pl: "Uroda",
    },
  },
  {
    value: "nature",
    emoji: "🌿",
    labels: {
      ru: "Природа",
      en: "Nature",
      de: "Natur",
      es: "Naturaleza",
      tr: "Doğa",
      fr: "Nature",
      it: "Natura",
      "pt-br": "Natureza",
      id: "Alam",
      pl: "Natura",
    },
  },
  {
    value: "animals",
    emoji: "🐾",
    labels: {
      ru: "Животные",
      en: "Animals",
      de: "Tiere",
      es: "Animales",
      tr: "Hayvanlar",
      fr: "Animaux",
      it: "Animali",
      "pt-br": "Animais",
      id: "Hewan",
      pl: "Zwierzęta",
    },
  },
  {
    value: "people",
    emoji: "🧑",
    labels: {
      ru: "Люди",
      en: "People",
      de: "Menschen",
      es: "Personas",
      tr: "İnsanlar",
      fr: "Personnes",
      it: "Persone",
      "pt-br": "Pessoas",
      id: "Orang",
      pl: "Ludzie",
    },
  },
  {
    value: "celebrities",
    emoji: "⭐",
    labels: {
      ru: "Звёзды",
      en: "Celebrities",
      de: "Promis",
      es: "Celebridades",
      tr: "Ünlüler",
      fr: "Célébrités",
      it: "Celebrità",
      "pt-br": "Celebridades",
      id: "Selebriti",
      pl: "Celebryci",
    },
  },
  {
    value: "marketing",
    emoji: "📣",
    labels: {
      ru: "Маркетинг",
      en: "Marketing",
      de: "Marketing",
      es: "Marketing",
      tr: "Pazarlama",
      fr: "Marketing",
      it: "Marketing",
      "pt-br": "Marketing",
      id: "Pemasaran",
      pl: "Marketing",
    },
  },
  {
    value: "startups",
    emoji: "🧪",
    labels: {
      ru: "Стартапы",
      en: "Startups",
      de: "Startups",
      es: "Startups",
      tr: "Girişimler",
      fr: "Startups",
      it: "Startup",
      "pt-br": "Startups",
      id: "Startup",
      pl: "Startupy",
    },
  },
  {
    value: "jobs",
    emoji: "🛠️",
    labels: {
      ru: "Работа",
      en: "Jobs",
      de: "Jobs",
      es: "Trabajo",
      tr: "İş",
      fr: "Emplois",
      it: "Lavoro",
      "pt-br": "Empregos",
      id: "Pekerjaan",
      pl: "Praca",
    },
  },
  {
    value: "real_estate",
    emoji: "🏠",
    labels: {
      ru: "Недвижимость",
      en: "Real estate",
      de: "Immobilien",
      es: "Bienes raíces",
      tr: "Gayrimenkul",
      fr: "Immobilier",
      it: "Immobiliare",
      "pt-br": "Imóveis",
      id: "Properti",
      pl: "Nieruchomości",
    },
  },
  {
    value: "auto",
    emoji: "🚗",
    labels: {
      ru: "Авто",
      en: "Auto",
      de: "Auto",
      es: "Autos",
      tr: "Otomobil",
      fr: "Auto",
      it: "Auto",
      "pt-br": "Auto",
      id: "Otomotif",
      pl: "Motoryzacja",
    },
  },
  {
    value: "creativity",
    emoji: "✨",
    labels: {
      ru: "Творчество",
      en: "Creativity",
      de: "Kreativität",
      es: "Creatividad",
      tr: "Yaratıcılık",
      fr: "Créativité",
      it: "Creatività",
      "pt-br": "Criatividade",
      id: "Kreativitas",
      pl: "Kreatywność",
    },
  },
];

export function getTagLabel(tag: SiteTag, locale: SiteLocale) {
  return `${tag.emoji} ${tag.labels[locale] ?? tag.labels.en}`;
}

export function findTagByValue(value: string) {
  return SITE_TAGS.find((tag) => tag.value === value);
}