import type { SiteLocale } from "./locales";

export type TagLabelMap = Record<SiteLocale, string>;

export type SiteTag = {
  value: string;
  emoji: string;
  labels: TagLabelMap;
};

export type SiteTagGroup = SiteTag & {
  children: SiteTag[];
};

const TAG_LABEL_TRANSLATIONS: Partial<Record<SiteLocale, Record<string, string>>> = {
  "ua": {
    "AI": "AI",
    "Advertising": "Реклама",
    "Advice": "Поради",
    "All": "Усе",
    "Analytics": "Аналітика",
    "Animals": "Тварини",
    "Art": "Арт",
    "Auto": "Авто",
    "Banks": "Банки",
    "Beauty": "Краса",
    "Blogs": "Блоги",
    "Body Shape": "Форма тіла",
    "Books": "Книги",
    "Bots": "Боти",
    "Branding": "Брендинг",
    "Brands": "Бренди",
    "Breaking": "Терміново",
    "Business": "Бізнес",
    "Cases": "Кейси",
    "Career": "Кар’єра",
    "Celebrities": "Зірки",
    "Championships": "Чемпіонати",
    "Channels": "Канали",
    "Cinema": "Кіно",
    "Companies": "Компанії",
    "Conflicts": "Конфлікти",
    "Console": "Консолі",
    "Construction": "Будівництво",
    "Construction Equipment": "Будівельна техніка",
    "Countries": "Країни",
    "Courses": "Курси",
    "Creativity": "Творчість",
    "Crypto": "Крипта",
    "Culture": "Культура",
    "Delivery": "Доставка",
    "Design": "Дизайн",
    "Development": "Розробка",
    "Discoveries": "Відкриття",
    "E-commerce": "E-commerce",
    "Ecology": "Екологія",
    "Economy": "Економіка",
    "Education": "Освіта",
    "Elections": "Вибори",
    "Electronics": "Електроніка",
    "Energy": "Енергетика",
    "Entrepreneurship": "Підприємництво",
    "Esports": "Кіберспорт",
    "Fashion": "Мода",
    "Finance": "Фінанси",
    "Fitness": "Фітнес",
    "Food": "Їжа",
    "Food Delivery": "Доставка їжі",
    "Food Service": "Заклади харчування",
    "Food Service Jobs": "Робота в закладах",
    "Founders": "Фаундери",
    "Freelance": "Фриланс",
    "Gadgets": "Гаджети",
    "Gaming": "Ігри",
    "Good News": "Добрі новини",
    "Government": "Влада",
    "Handmade": "Handmade",
    "Health": "Здоров’я",
    "History": "Історія",
    "Home Appliances": "Побутова техніка",
    "Hotels": "Готелі",
    "Housing": "Житло",
    "Humor": "Гумор",
    "Incidents": "Події",
    "Industry": "Промисловість",
    "Inspiration": "Натхнення",
    "Internet": "Інтернет",
    "Interviews": "Інтерв’ю",
    "Investigations": "Розслідування",
    "Investing": "Інвестиції",
    "Investment": "Інвестиції",
    "Irony": "Іронія",
    "Job Learning": "Навчання професії",
    "Languages": "Мови",
    "Logistics": "Логістика",
    "Macroeconomy": "Макроекономіка",
    "Management": "Управління",
    "Marketing": "Маркетинг",
    "Marketplaces & Shops": "Маркетплейси та магазини",
    "Markets": "Ринки",
    "Matches": "Матчі",
    "Medicine": "Медицина",
    "Memes": "Меми",
    "Misc": "Різне",
    "Mobile Games": "Мобільні",
    "Moto": "Мото",
    "Music": "Музика",
    "Nature": "Природа",
    "New & Trending": "Новинки і тренди",
    "New Arrivals": "Новинки",
    "News": "Новини",
    "No Negative": "Без негативу",
    "Nutrition": "Харчування",
    "Opinion": "Думки",
    "Other": "Інше",
    "Other Transport": "Інший транспорт",
    "PC": "PC",
    "PC & Components": "PC та комплектуючі",
    "Parenting": "Батьківство",
    "Part-time": "Підробіток",
    "Payment Systems": "Платіжні системи",
    "People": "Люди",
    "Personal Finance": "Особисті фінанси",
    "Photography": "Фото",
    "Plants": "Рослини",
    "Politics": "Політика",
    "Products": "Продукти",
    "Psychology": "Психологія",
    "Real Estate": "Нерухомість",
    "Recipes": "Рецепти",
    "Regions & Countries": "Регіони і країни",
    "Relationships": "Стосунки",
    "Remote": "Віддалено",
    "Research": "Дослідження",
    "Restaurants / Cafes / Bars": "Ресторани / кафе / бари",
    "Resume": "Резюме",
    "Reviews": "Відгуки",
    "Routes": "Маршрути",
    "SMM": "SMM",
    "Satire": "Сатира",
    "Science": "Наука",
    "Self-awareness": "Самопізнання",
    "Self-development": "Саморозвиток",
    "Series": "Серіали",
    "Shops & Brands": "Магазини і бренди",
    "Software": "Софт",
    "Software & Marketing": "Софт і просування",
    "Space": "Космос",
    "Sports": "Спорт",
    "Sports News": "Спортивні новини",
    "Startups": "Стартапи",
    "Style": "Стиль",
    "TON": "TON",
    "Technology": "Технології",
    "Telegram": "Telegram",
    "Trading": "Трейдинг",
    "Training": "Тренування",
    "Transfers": "Трансфери",
    "Transport": "Транспорт",
    "Travel": "Подорожі",
    "Updates": "Оновлення",
    "Vacancies": "Вакансії",
    "Vacation": "Відпочинок",
    "War": "Війна",
    "Web & Apps": "Сайти і застосунки",
    "Work": "Робота",
    "World": "Світ",
    "World Politics": "Світова політика"
  },
  "cn": {
    "AI": "AI",
    "Advertising": "广告",
    "Advice": "建议",
    "All": "全部",
    "Analytics": "分析",
    "Animals": "动物",
    "Art": "艺术",
    "Auto": "汽车",
    "Banks": "银行",
    "Beauty": "美妆",
    "Blogs": "博客",
    "Body Shape": "身材",
    "Books": "书籍",
    "Bots": "机器人",
    "Branding": "品牌建设",
    "Brands": "品牌",
    "Breaking": "突发",
    "Business": "商业",
    "Cases": "案例",
    "Career": "职业发展",
    "Celebrities": "明星",
    "Championships": "锦标赛",
    "Channels": "频道",
    "Cinema": "电影",
    "Companies": "公司",
    "Conflicts": "冲突",
    "Console": "主机",
    "Construction": "建筑",
    "Construction Equipment": "建筑设备",
    "Countries": "国家",
    "Courses": "课程",
    "Creativity": "创意",
    "Crypto": "加密货币",
    "Culture": "文化",
    "Delivery": "配送",
    "Design": "设计",
    "Development": "开发",
    "Discoveries": "发现",
    "E-commerce": "电商",
    "Ecology": "生态",
    "Economy": "经济",
    "Education": "教育",
    "Elections": "选举",
    "Electronics": "电子产品",
    "Energy": "能源",
    "Entrepreneurship": "创业",
    "Esports": "电竞",
    "Fashion": "时尚",
    "Finance": "金融",
    "Fitness": "健身",
    "Food": "美食",
    "Food Delivery": "外卖",
    "Food Service": "餐饮",
    "Food Service Jobs": "餐饮工作",
    "Founders": "创始人",
    "Freelance": "自由职业",
    "Gadgets": "数码设备",
    "Gaming": "游戏",
    "Good News": "好消息",
    "Government": "政府",
    "Handmade": "手作",
    "Health": "健康",
    "History": "历史",
    "Home Appliances": "家电",
    "Hotels": "酒店",
    "Housing": "住房",
    "Humor": "幽默",
    "Incidents": "事件",
    "Industry": "工业",
    "Inspiration": "灵感",
    "Internet": "互联网",
    "Interviews": "访谈",
    "Investigations": "调查",
    "Investing": "投资",
    "Investment": "投资",
    "Irony": "讽刺",
    "Job Learning": "职业学习",
    "Languages": "语言",
    "Logistics": "物流",
    "Macroeconomy": "宏观经济",
    "Management": "管理",
    "Marketing": "营销",
    "Marketplaces & Shops": "平台与商店",
    "Markets": "市场",
    "Matches": "比赛",
    "Medicine": "医学",
    "Memes": "梗图",
    "Misc": "杂项",
    "Mobile Games": "手游",
    "Moto": "摩托",
    "Music": "音乐",
    "Nature": "自然",
    "New & Trending": "新品与趋势",
    "New Arrivals": "新品",
    "News": "新闻",
    "No Negative": "无负面",
    "Nutrition": "营养",
    "Opinion": "观点",
    "Other": "其他",
    "Other Transport": "其他交通",
    "PC": "PC",
    "PC & Components": "电脑与配件",
    "Parenting": "育儿",
    "Part-time": "兼职",
    "Payment Systems": "支付系统",
    "People": "人物",
    "Personal Finance": "个人理财",
    "Photography": "摄影",
    "Plants": "植物",
    "Politics": "政治",
    "Products": "产品",
    "Psychology": "心理学",
    "Real Estate": "房地产",
    "Recipes": "食谱",
    "Regions & Countries": "地区与国家",
    "Relationships": "关系",
    "Remote": "远程",
    "Research": "研究",
    "Restaurants / Cafes / Bars": "餐厅 / 咖啡馆 / 酒吧",
    "Resume": "简历",
    "Reviews": "评价",
    "Routes": "路线",
    "SMM": "SMM",
    "Satire": "讽刺文学",
    "Science": "科学",
    "Self-awareness": "自我认知",
    "Self-development": "自我提升",
    "Series": "剧集",
    "Shops & Brands": "商店与品牌",
    "Software": "软件",
    "Software & Marketing": "软件与推广",
    "Space": "太空",
    "Sports": "体育",
    "Sports News": "体育新闻",
    "Startups": "创业公司",
    "Style": "风格",
    "TON": "TON",
    "Technology": "科技",
    "Telegram": "Telegram",
    "Trading": "交易",
    "Training": "训练",
    "Transfers": "转会",
    "Transport": "交通",
    "Travel": "旅行",
    "Updates": "更新",
    "Vacancies": "职位",
    "Vacation": "度假",
    "War": "战争",
    "Web & Apps": "网站与应用",
    "Work": "工作",
    "World": "世界",
    "World Politics": "国际政治"
  },
  "de": {
    "AI": "KI",
    "Advertising": "Werbung",
    "Advice": "Ratgeber",
    "All": "Alle",
    "Analytics": "Analytik",
    "Animals": "Tiere",
    "Art": "Kunst",
    "Auto": "Auto",
    "Banks": "Banken",
    "Beauty": "Beauty",
    "Blogs": "Blogs",
    "Body Shape": "Körperform",
    "Books": "Bücher",
    "Bots": "Bots",
    "Branding": "Branding",
    "Brands": "Marken",
    "Breaking": "Eilmeldung",
    "Business": "Business",
    "Cases": "Cases",
    "Career": "Karriere",
    "Celebrities": "Promis",
    "Championships": "Meisterschaften",
    "Channels": "Kanäle",
    "Cinema": "Kino",
    "Companies": "Unternehmen",
    "Conflicts": "Konflikte",
    "Console": "Konsole",
    "Construction": "Bau",
    "Construction Equipment": "Baumaschinen",
    "Countries": "Länder",
    "Courses": "Kurse",
    "Creativity": "Kreativität",
    "Crypto": "Krypto",
    "Culture": "Kultur",
    "Delivery": "Lieferung",
    "Design": "Design",
    "Development": "Entwicklung",
    "Discoveries": "Entdeckungen",
    "E-commerce": "E-Commerce",
    "Ecology": "Ökologie",
    "Economy": "Wirtschaft",
    "Education": "Bildung",
    "Elections": "Wahlen",
    "Electronics": "Elektronik",
    "Energy": "Energie",
    "Entrepreneurship": "Unternehmertum",
    "Esports": "E-Sport",
    "Fashion": "Mode",
    "Finance": "Finanzen",
    "Fitness": "Fitness",
    "Food": "Essen",
    "Food Delivery": "Essenslieferung",
    "Food Service": "Gastronomie",
    "Food Service Jobs": "Gastro-Jobs",
    "Founders": "Gründer",
    "Freelance": "Freelance",
    "Gadgets": "Gadgets",
    "Gaming": "Gaming",
    "Good News": "Gute Nachrichten",
    "Government": "Regierung",
    "Handmade": "Handmade",
    "Health": "Gesundheit",
    "History": "Geschichte",
    "Home Appliances": "Haushaltsgeräte",
    "Hotels": "Hotels",
    "Housing": "Wohnen",
    "Humor": "Humor",
    "Incidents": "Vorfälle",
    "Industry": "Industrie",
    "Inspiration": "Inspiration",
    "Internet": "Internet",
    "Interviews": "Interviews",
    "Investigations": "Recherchen",
    "Investing": "Investieren",
    "Investment": "Investment",
    "Irony": "Ironie",
    "Job Learning": "Berufsausbildung",
    "Languages": "Sprachen",
    "Logistics": "Logistik",
    "Macroeconomy": "Makroökonomie",
    "Management": "Management",
    "Marketing": "Marketing",
    "Marketplaces & Shops": "Marktplätze & Shops",
    "Markets": "Märkte",
    "Matches": "Spiele",
    "Medicine": "Medizin",
    "Memes": "Memes",
    "Misc": "Verschiedenes",
    "Mobile Games": "Mobile Spiele",
    "Moto": "Motorrad",
    "Music": "Musik",
    "Nature": "Natur",
    "New & Trending": "Neu & Trends",
    "New Arrivals": "Neuheiten",
    "News": "Nachrichten",
    "No Negative": "Ohne Negatives",
    "Nutrition": "Ernährung",
    "Opinion": "Meinungen",
    "Other": "Andere",
    "Other Transport": "Anderer Transport",
    "PC": "PC",
    "PC & Components": "PC & Komponenten",
    "Parenting": "Elternschaft",
    "Part-time": "Teilzeit",
    "Payment Systems": "Zahlungssysteme",
    "People": "Menschen",
    "Personal Finance": "Private Finanzen",
    "Photography": "Fotografie",
    "Plants": "Pflanzen",
    "Politics": "Politik",
    "Products": "Produkte",
    "Psychology": "Psychologie",
    "Real Estate": "Immobilien",
    "Recipes": "Rezepte",
    "Regions & Countries": "Regionen & Länder",
    "Relationships": "Beziehungen",
    "Remote": "Remote",
    "Research": "Forschung",
    "Restaurants / Cafes / Bars": "Restaurants / Cafés / Bars",
    "Resume": "Lebenslauf",
    "Reviews": "Bewertungen",
    "Routes": "Routen",
    "SMM": "SMM",
    "Satire": "Satire",
    "Science": "Wissenschaft",
    "Self-awareness": "Selbsterkenntnis",
    "Self-development": "Selbstentwicklung",
    "Series": "Serien",
    "Shops & Brands": "Shops & Marken",
    "Software": "Software",
    "Software & Marketing": "Software & Marketing",
    "Space": "Weltraum",
    "Sports": "Sport",
    "Sports News": "Sportnachrichten",
    "Startups": "Startups",
    "Style": "Stil",
    "TON": "TON",
    "Technology": "Technologie",
    "Telegram": "Telegram",
    "Trading": "Trading",
    "Training": "Training",
    "Transfers": "Transfers",
    "Transport": "Transport",
    "Travel": "Reisen",
    "Updates": "Updates",
    "Vacancies": "Stellenangebote",
    "Vacation": "Urlaub",
    "War": "Krieg",
    "Web & Apps": "Web & Apps",
    "Work": "Arbeit",
    "World": "Welt",
    "World Politics": "Weltpolitik"
  },
  "es": {
    "AI": "IA",
    "Advertising": "Publicidad",
    "Advice": "Consejos",
    "All": "Todo",
    "Analytics": "Analítica",
    "Animals": "Animales",
    "Art": "Arte",
    "Auto": "Autos",
    "Banks": "Bancos",
    "Beauty": "Belleza",
    "Blogs": "Blogs",
    "Body Shape": "Forma física",
    "Books": "Libros",
    "Bots": "Bots",
    "Branding": "Branding",
    "Brands": "Marcas",
    "Breaking": "Urgente",
    "Business": "Negocios",
    "Cases": "Casos",
    "Celebrities": "Celebridades",
    "Championships": "Campeonatos",
    "Channels": "Canales",
    "Cinema": "Cine",
    "Companies": "Empresas",
    "Conflicts": "Conflictos",
    "Console": "Consolas",
    "Construction": "Construcción",
    "Construction Equipment": "Equipos de construcción",
    "Countries": "Países",
    "Courses": "Cursos",
    "Creativity": "Creatividad",
    "Crypto": "Cripto",
    "Culture": "Cultura",
    "Delivery": "Entrega",
    "Design": "Diseño",
    "Development": "Desarrollo",
    "Discoveries": "Descubrimientos",
    "E-commerce": "E-commerce",
    "Ecology": "Ecología",
    "Economy": "Economía",
    "Education": "Educación",
    "Elections": "Elecciones",
    "Electronics": "Electrónica",
    "Energy": "Energía",
    "Entrepreneurship": "Emprendimiento",
    "Esports": "Esports",
    "Fashion": "Moda",
    "Finance": "Finanzas",
    "Fitness": "Fitness",
    "Food": "Comida",
    "Food Delivery": "Entrega de comida",
    "Food Service": "Restauración",
    "Food Service Jobs": "Trabajos en restauración",
    "Founders": "Fundadores",
    "Freelance": "Freelance",
    "Gadgets": "Gadgets",
    "Gaming": "Juegos",
    "Good News": "Buenas noticias",
    "Government": "Gobierno",
    "Handmade": "Hecho a mano",
    "Health": "Salud",
    "History": "Historia",
    "Home Appliances": "Electrodomésticos",
    "Housing": "Vivienda",
    "Humor": "Humor",
    "Incidents": "Incidentes",
    "Industry": "Industria",
    "Inspiration": "Inspiración",
    "Internet": "Internet",
    "Interviews": "Entrevistas",
    "Investing": "Inversiones",
    "Investment": "Inversión",
    "Irony": "Ironía",
    "Job Learning": "Formación profesional",
    "Languages": "Idiomas",
    "Logistics": "Logística",
    "Macroeconomy": "Macroeconomía",
    "Management": "Gestión",
    "Marketing": "Marketing",
    "Marketplaces & Shops": "Marketplaces y tiendas",
    "Markets": "Mercados",
    "Matches": "Partidos",
    "Medicine": "Medicina",
    "Memes": "Memes",
    "Misc": "Varios",
    "Mobile Games": "Juegos móviles",
    "Moto": "Motos",
    "Music": "Música",
    "Nature": "Naturaleza",
    "New & Trending": "Novedades y tendencias",
    "New Arrivals": "Novedades",
    "News": "Noticias",
    "No Negative": "Sin negatividad",
    "Nutrition": "Nutrición",
    "Opinion": "Opinión",
    "Other": "Otro",
    "Other Transport": "Otro transporte",
    "PC": "PC",
    "PC & Components": "PC y componentes",
    "Parenting": "Crianza",
    "Part-time": "Media jornada",
    "Payment Systems": "Sistemas de pago",
    "People": "Personas",
    "Personal Finance": "Finanzas personales",
    "Photography": "Fotografía",
    "Plants": "Plantas",
    "Politics": "Política",
    "Products": "Productos",
    "Psychology": "Psicología",
    "Real Estate": "Bienes raíces",
    "Recipes": "Recetas",
    "Regions & Countries": "Regiones y países",
    "Relationships": "Relaciones",
    "Remote": "Remoto",
    "Research": "Investigación",
    "Restaurants / Cafes / Bars": "Restaurantes / cafés / bares",
    "Resume": "CV",
    "Reviews": "Reseñas",
    "Routes": "Rutas",
    "SMM": "SMM",
    "Satire": "Sátira",
    "Science": "Ciencia",
    "Self-awareness": "Autoconocimiento",
    "Self-development": "Desarrollo personal",
    "Series": "Series",
    "Shops & Brands": "Tiendas y marcas",
    "Software": "Software",
    "Software & Marketing": "Software y marketing",
    "Space": "Espacio",
    "Sports": "Deportes",
    "Sports News": "Noticias deportivas",
    "Startups": "Startups",
    "Style": "Estilo",
    "TON": "TON",
    "Technology": "Tecnología",
    "Telegram": "Telegram",
    "Trading": "Trading",
    "Training": "Entrenamiento",
    "Transfers": "Transferencias",
    "Transport": "Transporte",
    "Travel": "Viajes",
    "Updates": "Actualizaciones",
    "Vacancies": "Vacantes",
    "Vacation": "Vacaciones",
    "War": "Guerra",
    "Web & Apps": "Web y apps",
    "Work": "Trabajo",
    "World": "Mundo",
    "World Politics": "Política mundial",
    "Career": "Carrera",
    "Hotels": "Hoteles",
    "Investigations": "Investigaciones"
  },
  "fr": {
    "AI": "IA",
    "Advertising": "Publicité",
    "Advice": "Conseils",
    "All": "Tout",
    "Analytics": "Analyse",
    "Animals": "Animaux",
    "Art": "Art",
    "Auto": "Auto",
    "Banks": "Banques",
    "Beauty": "Beauté",
    "Blogs": "Blogs",
    "Body Shape": "Forme du corps",
    "Books": "Livres",
    "Bots": "Bots",
    "Branding": "Branding",
    "Brands": "Marques",
    "Breaking": "Urgent",
    "Business": "Business",
    "Cases": "Cas pratiques",
    "Career": "Carrière",
    "Celebrities": "Célébrités",
    "Championships": "Championnats",
    "Channels": "Chaînes",
    "Cinema": "Cinéma",
    "Companies": "Entreprises",
    "Conflicts": "Conflits",
    "Console": "Consoles",
    "Construction": "Construction",
    "Construction Equipment": "Équipement de construction",
    "Countries": "Pays",
    "Courses": "Cours",
    "Creativity": "Créativité",
    "Crypto": "Crypto",
    "Culture": "Culture",
    "Delivery": "Livraison",
    "Design": "Design",
    "Development": "Développement",
    "Discoveries": "Découvertes",
    "E-commerce": "E-commerce",
    "Ecology": "Écologie",
    "Economy": "Économie",
    "Education": "Éducation",
    "Elections": "Élections",
    "Electronics": "Électronique",
    "Energy": "Énergie",
    "Entrepreneurship": "Entrepreneuriat",
    "Esports": "Esport",
    "Fashion": "Mode",
    "Finance": "Finance",
    "Fitness": "Fitness",
    "Food": "Cuisine",
    "Food Delivery": "Livraison de repas",
    "Food Service": "Restauration",
    "Food Service Jobs": "Emplois en restauration",
    "Founders": "Fondateurs",
    "Freelance": "Freelance",
    "Gadgets": "Gadgets",
    "Gaming": "Jeux",
    "Good News": "Bonnes nouvelles",
    "Government": "Gouvernement",
    "Handmade": "Fait main",
    "Health": "Santé",
    "History": "Histoire",
    "Home Appliances": "Électroménager",
    "Hotels": "Hôtels",
    "Housing": "Logement",
    "Humor": "Humour",
    "Incidents": "Incidents",
    "Industry": "Industrie",
    "Inspiration": "Inspiration",
    "Internet": "Internet",
    "Interviews": "Interviews",
    "Investigations": "Enquêtes",
    "Investing": "Investissement",
    "Investment": "Investissement",
    "Irony": "Ironie",
    "Job Learning": "Formation professionnelle",
    "Languages": "Langues",
    "Logistics": "Logistique",
    "Macroeconomy": "Macroéconomie",
    "Management": "Gestion",
    "Marketing": "Marketing",
    "Marketplaces & Shops": "Marketplaces et boutiques",
    "Markets": "Marchés",
    "Matches": "Matchs",
    "Medicine": "Médecine",
    "Memes": "Mèmes",
    "Misc": "Divers",
    "Mobile Games": "Jeux mobiles",
    "Moto": "Moto",
    "Music": "Musique",
    "Nature": "Nature",
    "New & Trending": "Nouveautés et tendances",
    "New Arrivals": "Nouveautés",
    "News": "Actualités",
    "No Negative": "Sans négatif",
    "Nutrition": "Nutrition",
    "Opinion": "Opinions",
    "Other": "Autre",
    "Other Transport": "Autre transport",
    "PC": "PC",
    "PC & Components": "PC et composants",
    "Parenting": "Parentalité",
    "Part-time": "Temps partiel",
    "Payment Systems": "Systèmes de paiement",
    "People": "Personnes",
    "Personal Finance": "Finances personnelles",
    "Photography": "Photo",
    "Plants": "Plantes",
    "Politics": "Politique",
    "Products": "Produits",
    "Psychology": "Psychologie",
    "Real Estate": "Immobilier",
    "Recipes": "Recettes",
    "Regions & Countries": "Régions et pays",
    "Relationships": "Relations",
    "Remote": "Télétravail",
    "Research": "Recherche",
    "Restaurants / Cafes / Bars": "Restaurants / cafés / bars",
    "Resume": "CV",
    "Reviews": "Avis",
    "Routes": "Itinéraires",
    "SMM": "SMM",
    "Satire": "Satire",
    "Science": "Science",
    "Self-awareness": "Connaissance de soi",
    "Self-development": "Développement personnel",
    "Series": "Séries",
    "Shops & Brands": "Boutiques et marques",
    "Software": "Logiciel",
    "Software & Marketing": "Logiciel et marketing",
    "Space": "Espace",
    "Sports": "Sport",
    "Sports News": "Actualités sportives",
    "Startups": "Startups",
    "Style": "Style",
    "TON": "TON",
    "Technology": "Technologie",
    "Telegram": "Telegram",
    "Trading": "Trading",
    "Training": "Entraînement",
    "Transfers": "Transferts",
    "Transport": "Transport",
    "Travel": "Voyage",
    "Updates": "Mises à jour",
    "Vacancies": "Offres d’emploi",
    "Vacation": "Vacances",
    "War": "Guerre",
    "Web & Apps": "Web et apps",
    "Work": "Travail",
    "World": "Monde",
    "World Politics": "Politique mondiale"
  },
  "it": {
    "AI": "IA",
    "Advertising": "Pubblicità",
    "Advice": "Consigli",
    "All": "Tutto",
    "Analytics": "Analitica",
    "Animals": "Animali",
    "Art": "Arte",
    "Auto": "Auto",
    "Banks": "Banche",
    "Beauty": "Bellezza",
    "Blogs": "Blog",
    "Body Shape": "Forma fisica",
    "Books": "Libri",
    "Bots": "Bot",
    "Branding": "Branding",
    "Brands": "Brand",
    "Breaking": "Urgente",
    "Business": "Business",
    "Cases": "Casi",
    "Career": "Carriera",
    "Celebrities": "Celebrità",
    "Championships": "Campionati",
    "Channels": "Canali",
    "Cinema": "Cinema",
    "Companies": "Aziende",
    "Conflicts": "Conflitti",
    "Console": "Console",
    "Construction": "Costruzione",
    "Construction Equipment": "Attrezzature edili",
    "Countries": "Paesi",
    "Courses": "Corsi",
    "Creativity": "Creatività",
    "Crypto": "Crypto",
    "Culture": "Cultura",
    "Delivery": "Consegna",
    "Design": "Design",
    "Development": "Sviluppo",
    "Discoveries": "Scoperte",
    "E-commerce": "E-commerce",
    "Ecology": "Ecologia",
    "Economy": "Economia",
    "Education": "Istruzione",
    "Elections": "Elezioni",
    "Electronics": "Elettronica",
    "Energy": "Energia",
    "Entrepreneurship": "Imprenditorialità",
    "Esports": "Esport",
    "Fashion": "Moda",
    "Finance": "Finanza",
    "Fitness": "Fitness",
    "Food": "Cibo",
    "Food Delivery": "Consegna cibo",
    "Food Service": "Ristorazione",
    "Food Service Jobs": "Lavori nella ristorazione",
    "Founders": "Founder",
    "Freelance": "Freelance",
    "Gadgets": "Gadget",
    "Gaming": "Giochi",
    "Good News": "Buone notizie",
    "Government": "Governo",
    "Handmade": "Fatto a mano",
    "Health": "Salute",
    "History": "Storia",
    "Home Appliances": "Elettrodomestici",
    "Hotels": "Hotel",
    "Housing": "Abitazioni",
    "Humor": "Umorismo",
    "Incidents": "Incidenti",
    "Industry": "Industria",
    "Inspiration": "Ispirazione",
    "Internet": "Internet",
    "Interviews": "Interviste",
    "Investigations": "Inchieste",
    "Investing": "Investimenti",
    "Investment": "Investimento",
    "Irony": "Ironia",
    "Job Learning": "Formazione professionale",
    "Languages": "Lingue",
    "Logistics": "Logistica",
    "Macroeconomy": "Macroeconomia",
    "Management": "Gestione",
    "Marketing": "Marketing",
    "Marketplaces & Shops": "Marketplace e negozi",
    "Markets": "Mercati",
    "Matches": "Partite",
    "Medicine": "Medicina",
    "Memes": "Meme",
    "Misc": "Varie",
    "Mobile Games": "Giochi mobile",
    "Moto": "Moto",
    "Music": "Musica",
    "Nature": "Natura",
    "New & Trending": "Novità e trend",
    "New Arrivals": "Novità",
    "News": "Notizie",
    "No Negative": "Senza negatività",
    "Nutrition": "Nutrizione",
    "Opinion": "Opinioni",
    "Other": "Altro",
    "Other Transport": "Altro trasporto",
    "PC": "PC",
    "PC & Components": "PC e componenti",
    "Parenting": "Genitorialità",
    "Part-time": "Part-time",
    "Payment Systems": "Sistemi di pagamento",
    "People": "Persone",
    "Personal Finance": "Finanza personale",
    "Photography": "Foto",
    "Plants": "Piante",
    "Politics": "Politica",
    "Products": "Prodotti",
    "Psychology": "Psicologia",
    "Real Estate": "Immobiliare",
    "Recipes": "Ricette",
    "Regions & Countries": "Regioni e paesi",
    "Relationships": "Relazioni",
    "Remote": "Remoto",
    "Research": "Ricerca",
    "Restaurants / Cafes / Bars": "Ristoranti / caffè / bar",
    "Resume": "CV",
    "Reviews": "Recensioni",
    "Routes": "Itinerari",
    "SMM": "SMM",
    "Satire": "Satira",
    "Science": "Scienza",
    "Self-awareness": "Consapevolezza di sé",
    "Self-development": "Crescita personale",
    "Series": "Serie",
    "Shops & Brands": "Negozi e brand",
    "Software": "Software",
    "Software & Marketing": "Software e marketing",
    "Space": "Spazio",
    "Sports": "Sport",
    "Sports News": "Notizie sportive",
    "Startups": "Startup",
    "Style": "Stile",
    "TON": "TON",
    "Technology": "Tecnologia",
    "Telegram": "Telegram",
    "Trading": "Trading",
    "Training": "Allenamento",
    "Transfers": "Trasferimenti",
    "Transport": "Trasporti",
    "Travel": "Viaggi",
    "Updates": "Aggiornamenti",
    "Vacancies": "Offerte",
    "Vacation": "Vacanze",
    "War": "Guerra",
    "Web & Apps": "Web e app",
    "Work": "Lavoro",
    "World": "Mondo",
    "World Politics": "Politica mondiale"
  },
  "br": {
    "AI": "IA",
    "Advertising": "Publicidade",
    "Advice": "Conselhos",
    "All": "Tudo",
    "Analytics": "Análises",
    "Animals": "Animais",
    "Art": "Arte",
    "Auto": "Auto",
    "Banks": "Bancos",
    "Beauty": "Beleza",
    "Blogs": "Blogs",
    "Body Shape": "Forma física",
    "Books": "Livros",
    "Bots": "Bots",
    "Branding": "Branding",
    "Brands": "Marcas",
    "Breaking": "Urgente",
    "Business": "Negócios",
    "Cases": "Casos",
    "Career": "Carreira",
    "Celebrities": "Celebridades",
    "Championships": "Campeonatos",
    "Channels": "Canais",
    "Cinema": "Cinema",
    "Companies": "Empresas",
    "Conflicts": "Conflitos",
    "Console": "Consoles",
    "Construction": "Construção",
    "Construction Equipment": "Equipamentos de construção",
    "Countries": "Países",
    "Courses": "Cursos",
    "Creativity": "Criatividade",
    "Crypto": "Cripto",
    "Culture": "Cultura",
    "Delivery": "Entrega",
    "Design": "Design",
    "Development": "Desenvolvimento",
    "Discoveries": "Descobertas",
    "E-commerce": "E-commerce",
    "Ecology": "Ecologia",
    "Economy": "Economia",
    "Education": "Educação",
    "Elections": "Eleições",
    "Electronics": "Eletrônicos",
    "Energy": "Energia",
    "Entrepreneurship": "Empreendedorismo",
    "Esports": "Esports",
    "Fashion": "Moda",
    "Finance": "Finanças",
    "Fitness": "Fitness",
    "Food": "Comida",
    "Food Delivery": "Entrega de comida",
    "Food Service": "Alimentação fora de casa",
    "Food Service Jobs": "Trabalhos em alimentação",
    "Founders": "Fundadores",
    "Freelance": "Freelance",
    "Gadgets": "Gadgets",
    "Gaming": "Games",
    "Good News": "Boas notícias",
    "Government": "Governo",
    "Handmade": "Feito à mão",
    "Health": "Saúde",
    "History": "História",
    "Home Appliances": "Eletrodomésticos",
    "Hotels": "Hotéis",
    "Housing": "Moradia",
    "Humor": "Humor",
    "Incidents": "Incidentes",
    "Industry": "Indústria",
    "Inspiration": "Inspiração",
    "Internet": "Internet",
    "Interviews": "Entrevistas",
    "Investigations": "Investigações",
    "Investing": "Investimentos",
    "Investment": "Investimento",
    "Irony": "Ironia",
    "Job Learning": "Formação profissional",
    "Languages": "Idiomas",
    "Logistics": "Logística",
    "Macroeconomy": "Macroeconomia",
    "Management": "Gestão",
    "Marketing": "Marketing",
    "Marketplaces & Shops": "Marketplaces e lojas",
    "Markets": "Mercados",
    "Matches": "Partidas",
    "Medicine": "Medicina",
    "Memes": "Memes",
    "Misc": "Diversos",
    "Mobile Games": "Jogos mobile",
    "Moto": "Moto",
    "Music": "Música",
    "Nature": "Natureza",
    "New & Trending": "Novidades e tendências",
    "New Arrivals": "Novidades",
    "News": "Notícias",
    "No Negative": "Sem negatividade",
    "Nutrition": "Nutrição",
    "Opinion": "Opiniões",
    "Other": "Outro",
    "Other Transport": "Outro transporte",
    "PC": "PC",
    "PC & Components": "PC e componentes",
    "Parenting": "Parentalidade",
    "Part-time": "Meio período",
    "Payment Systems": "Sistemas de pagamento",
    "People": "Pessoas",
    "Personal Finance": "Finanças pessoais",
    "Photography": "Foto",
    "Plants": "Plantas",
    "Politics": "Política",
    "Products": "Produtos",
    "Psychology": "Psicologia",
    "Real Estate": "Imóveis",
    "Recipes": "Receitas",
    "Regions & Countries": "Regiões e países",
    "Relationships": "Relacionamentos",
    "Remote": "Remoto",
    "Research": "Pesquisa",
    "Restaurants / Cafes / Bars": "Restaurantes / cafés / bares",
    "Resume": "Currículo",
    "Reviews": "Avaliações",
    "Routes": "Rotas",
    "SMM": "SMM",
    "Satire": "Sátira",
    "Science": "Ciência",
    "Self-awareness": "Autoconhecimento",
    "Self-development": "Desenvolvimento pessoal",
    "Series": "Séries",
    "Shops & Brands": "Lojas e marcas",
    "Software": "Software",
    "Software & Marketing": "Software e marketing",
    "Space": "Espaço",
    "Sports": "Esportes",
    "Sports News": "Notícias esportivas",
    "Startups": "Startups",
    "Style": "Estilo",
    "TON": "TON",
    "Technology": "Tecnologia",
    "Telegram": "Telegram",
    "Trading": "Trading",
    "Training": "Treino",
    "Transfers": "Transferências",
    "Transport": "Transporte",
    "Travel": "Viagens",
    "Updates": "Atualizações",
    "Vacancies": "Vagas",
    "Vacation": "Férias",
    "War": "Guerra",
    "Web & Apps": "Web e apps",
    "Work": "Trabalho",
    "World": "Mundo",
    "World Politics": "Política mundial"
  },
  "tr": {
    "AI": "AI",
    "Advertising": "Reklam",
    "Advice": "Tavsiyeler",
    "All": "Tümü",
    "Analytics": "Analitik",
    "Animals": "Hayvanlar",
    "Art": "Sanat",
    "Auto": "Oto",
    "Banks": "Bankalar",
    "Beauty": "Güzellik",
    "Blogs": "Bloglar",
    "Body Shape": "Vücut formu",
    "Books": "Kitaplar",
    "Bots": "Botlar",
    "Branding": "Markalaşma",
    "Brands": "Markalar",
    "Breaking": "Acil",
    "Business": "İş dünyası",
    "Cases": "Vakalar",
    "Career": "Kariyer",
    "Celebrities": "Ünlüler",
    "Championships": "Şampiyonalar",
    "Channels": "Kanallar",
    "Cinema": "Sinema",
    "Companies": "Şirketler",
    "Conflicts": "Çatışmalar",
    "Console": "Konsollar",
    "Construction": "İnşaat",
    "Construction Equipment": "İnşaat ekipmanı",
    "Countries": "Ülkeler",
    "Courses": "Kurslar",
    "Creativity": "Yaratıcılık",
    "Crypto": "Kripto",
    "Culture": "Kültür",
    "Delivery": "Teslimat",
    "Design": "Tasarım",
    "Development": "Geliştirme",
    "Discoveries": "Keşifler",
    "E-commerce": "E-ticaret",
    "Ecology": "Ekoloji",
    "Economy": "Ekonomi",
    "Education": "Eğitim",
    "Elections": "Seçimler",
    "Electronics": "Elektronik",
    "Energy": "Enerji",
    "Entrepreneurship": "Girişimcilik",
    "Esports": "E-spor",
    "Fashion": "Moda",
    "Finance": "Finans",
    "Fitness": "Fitness",
    "Food": "Yemek",
    "Food Delivery": "Yemek teslimatı",
    "Food Service": "Yeme-içme sektörü",
    "Food Service Jobs": "Yeme-içme işleri",
    "Founders": "Kurucular",
    "Freelance": "Freelance",
    "Gadgets": "Cihazlar",
    "Gaming": "Oyun",
    "Good News": "İyi haberler",
    "Government": "Hükümet",
    "Handmade": "El yapımı",
    "Health": "Sağlık",
    "History": "Tarih",
    "Home Appliances": "Ev aletleri",
    "Hotels": "Oteller",
    "Housing": "Konut",
    "Humor": "Mizah",
    "Incidents": "Olaylar",
    "Industry": "Sanayi",
    "Inspiration": "İlham",
    "Internet": "İnternet",
    "Interviews": "Röportajlar",
    "Investigations": "Araştırmalar",
    "Investing": "Yatırım",
    "Investment": "Yatırım",
    "Irony": "İroni",
    "Job Learning": "Mesleki eğitim",
    "Languages": "Diller",
    "Logistics": "Lojistik",
    "Macroeconomy": "Makroekonomi",
    "Management": "Yönetim",
    "Marketing": "Pazarlama",
    "Marketplaces & Shops": "Pazar yerleri ve mağazalar",
    "Markets": "Piyasalar",
    "Matches": "Maçlar",
    "Medicine": "Tıp",
    "Memes": "Mizah görselleri",
    "Misc": "Çeşitli",
    "Mobile Games": "Mobil oyunlar",
    "Moto": "Moto",
    "Music": "Müzik",
    "Nature": "Doğa",
    "New & Trending": "Yeniler ve trendler",
    "New Arrivals": "Yeniler",
    "News": "Haberler",
    "No Negative": "Negatif yok",
    "Nutrition": "Beslenme",
    "Opinion": "Görüşler",
    "Other": "Diğer",
    "Other Transport": "Diğer ulaşım",
    "PC": "PC",
    "PC & Components": "PC ve bileşenler",
    "Parenting": "Ebeveynlik",
    "Part-time": "Yarı zamanlı",
    "Payment Systems": "Ödeme sistemleri",
    "People": "İnsanlar",
    "Personal Finance": "Kişisel finans",
    "Photography": "Fotoğraf",
    "Plants": "Bitkiler",
    "Politics": "Politika",
    "Products": "Ürünler",
    "Psychology": "Psikoloji",
    "Real Estate": "Emlak",
    "Recipes": "Tarifler",
    "Regions & Countries": "Bölgeler ve ülkeler",
    "Relationships": "İlişkiler",
    "Remote": "Uzaktan",
    "Research": "Araştırma",
    "Restaurants / Cafes / Bars": "Restoranlar / kafeler / barlar",
    "Resume": "Özgeçmiş",
    "Reviews": "Yorumlar",
    "Routes": "Rotalar",
    "SMM": "SMM",
    "Satire": "Hiciv",
    "Science": "Bilim",
    "Self-awareness": "Öz farkındalık",
    "Self-development": "Kişisel gelişim",
    "Series": "Diziler",
    "Shops & Brands": "Mağazalar ve markalar",
    "Software": "Yazılım",
    "Software & Marketing": "Yazılım ve pazarlama",
    "Space": "Uzay",
    "Sports": "Spor",
    "Sports News": "Spor haberleri",
    "Startups": "Startup’lar",
    "Style": "Stil",
    "TON": "TON",
    "Technology": "Teknoloji",
    "Telegram": "Telegram",
    "Trading": "Al-sat",
    "Training": "Antrenman",
    "Transfers": "Transferler",
    "Transport": "Ulaşım",
    "Travel": "Seyahat",
    "Updates": "Güncellemeler",
    "Vacancies": "İlanlar",
    "Vacation": "Tatil",
    "War": "Savaş",
    "Web & Apps": "Web ve uygulamalar",
    "Work": "İş",
    "World": "Dünya",
    "World Politics": "Dünya politikası"
  },
  "id": {
    "AI": "AI",
    "Advertising": "Iklan",
    "Advice": "Saran",
    "All": "Semua",
    "Analytics": "Analitik",
    "Animals": "Hewan",
    "Art": "Seni",
    "Auto": "Mobil",
    "Banks": "Bank",
    "Beauty": "Kecantikan",
    "Blogs": "Blog",
    "Body Shape": "Bentuk tubuh",
    "Books": "Buku",
    "Bots": "Bot",
    "Branding": "Branding",
    "Brands": "Merek",
    "Breaking": "Mendesak",
    "Business": "Bisnis",
    "Cases": "Kasus",
    "Career": "Karier",
    "Celebrities": "Selebriti",
    "Championships": "Kejuaraan",
    "Channels": "Channel",
    "Cinema": "Film",
    "Companies": "Perusahaan",
    "Conflicts": "Konflik",
    "Console": "Konsol",
    "Construction": "Konstruksi",
    "Construction Equipment": "Peralatan konstruksi",
    "Countries": "Negara",
    "Courses": "Kursus",
    "Creativity": "Kreativitas",
    "Crypto": "Kripto",
    "Culture": "Budaya",
    "Delivery": "Pengiriman",
    "Design": "Desain",
    "Development": "Pengembangan",
    "Discoveries": "Penemuan",
    "E-commerce": "E-commerce",
    "Ecology": "Ekologi",
    "Economy": "Ekonomi",
    "Education": "Pendidikan",
    "Elections": "Pemilu",
    "Electronics": "Elektronik",
    "Energy": "Energi",
    "Entrepreneurship": "Kewirausahaan",
    "Esports": "Esports",
    "Fashion": "Mode",
    "Finance": "Keuangan",
    "Fitness": "Fitness",
    "Food": "Makanan",
    "Food Delivery": "Pengiriman makanan",
    "Food Service": "Kuliner",
    "Food Service Jobs": "Pekerjaan kuliner",
    "Founders": "Founder",
    "Freelance": "Freelance",
    "Gadgets": "Gadget",
    "Gaming": "Game",
    "Good News": "Kabar baik",
    "Government": "Pemerintah",
    "Handmade": "Buatan tangan",
    "Health": "Kesehatan",
    "History": "Sejarah",
    "Home Appliances": "Peralatan rumah",
    "Hotels": "Hotel",
    "Housing": "Perumahan",
    "Humor": "Humor",
    "Incidents": "Insiden",
    "Industry": "Industri",
    "Inspiration": "Inspirasi",
    "Internet": "Internet",
    "Interviews": "Wawancara",
    "Investigations": "Investigasi",
    "Investing": "Investasi",
    "Investment": "Investasi",
    "Irony": "Ironi",
    "Job Learning": "Belajar profesi",
    "Languages": "Bahasa",
    "Logistics": "Logistik",
    "Macroeconomy": "Makroekonomi",
    "Management": "Manajemen",
    "Marketing": "Marketing",
    "Marketplaces & Shops": "Marketplace & toko",
    "Markets": "Pasar",
    "Matches": "Pertandingan",
    "Medicine": "Medis",
    "Memes": "Meme",
    "Misc": "Lain-lain",
    "Mobile Games": "Game mobile",
    "Moto": "Motor",
    "Music": "Musik",
    "Nature": "Alam",
    "New & Trending": "Baru & tren",
    "New Arrivals": "Pendatang baru",
    "News": "Berita",
    "No Negative": "Tanpa negatif",
    "Nutrition": "Nutrisi",
    "Opinion": "Opini",
    "Other": "Lainnya",
    "Other Transport": "Transportasi lain",
    "PC": "PC",
    "PC & Components": "PC & komponen",
    "Parenting": "Parenting",
    "Part-time": "Paruh waktu",
    "Payment Systems": "Sistem pembayaran",
    "People": "Orang",
    "Personal Finance": "Keuangan pribadi",
    "Photography": "Foto",
    "Plants": "Tanaman",
    "Politics": "Politik",
    "Products": "Produk",
    "Psychology": "Psikologi",
    "Real Estate": "Properti",
    "Recipes": "Resep",
    "Regions & Countries": "Wilayah & negara",
    "Relationships": "Hubungan",
    "Remote": "Remote",
    "Research": "Riset",
    "Restaurants / Cafes / Bars": "Restoran / kafe / bar",
    "Resume": "CV",
    "Reviews": "Ulasan",
    "Routes": "Rute",
    "SMM": "SMM",
    "Satire": "Satire",
    "Science": "Sains",
    "Self-awareness": "Kesadaran diri",
    "Self-development": "Pengembangan diri",
    "Series": "Serial",
    "Shops & Brands": "Toko & merek",
    "Software": "Software",
    "Software & Marketing": "Software & marketing",
    "Space": "Antariksa",
    "Sports": "Olahraga",
    "Sports News": "Berita olahraga",
    "Startups": "Startup",
    "Style": "Gaya",
    "TON": "TON",
    "Technology": "Teknologi",
    "Telegram": "Telegram",
    "Trading": "Trading",
    "Training": "Latihan",
    "Transfers": "Transfer",
    "Transport": "Transportasi",
    "Travel": "Travel",
    "Updates": "Pembaruan",
    "Vacancies": "Lowongan",
    "Vacation": "Liburan",
    "War": "Perang",
    "Web & Apps": "Web & aplikasi",
    "Work": "Kerja",
    "World": "Dunia",
    "World Politics": "Politik dunia"
  },
  "my": {
    "AI": "AI",
    "Advertising": "Iklan",
    "Advice": "Saran",
    "All": "Semua",
    "Analytics": "Analitik",
    "Animals": "Haiwan",
    "Art": "Seni",
    "Auto": "Auto",
    "Banks": "Bank",
    "Beauty": "Kecantikan",
    "Blogs": "Blog",
    "Body Shape": "Bentuk tubuh",
    "Books": "Buku",
    "Bots": "Bot",
    "Branding": "Branding",
    "Brands": "Merek",
    "Breaking": "Mendesak",
    "Business": "Perniagaan",
    "Cases": "Kasus",
    "Career": "Kerjaya",
    "Celebrities": "Selebriti",
    "Championships": "Kejuaraan",
    "Channels": "Channel",
    "Cinema": "Filem",
    "Companies": "Syarikat",
    "Conflicts": "Konflik",
    "Console": "Konsol",
    "Construction": "Konstruksi",
    "Construction Equipment": "Peralatan konstruksi",
    "Countries": "Negara",
    "Courses": "Kursus",
    "Creativity": "Kreativitas",
    "Crypto": "Kripto",
    "Culture": "Budaya",
    "Delivery": "Penghantaran",
    "Design": "Desain",
    "Development": "Pembangunan",
    "Discoveries": "Penemuan",
    "E-commerce": "E-commerce",
    "Ecology": "Ekologi",
    "Economy": "Ekonomi",
    "Education": "Pendidikan",
    "Elections": "Pilihan raya",
    "Electronics": "Elektronik",
    "Energy": "Energi",
    "Entrepreneurship": "Keusahawanan",
    "Esports": "Esports",
    "Fashion": "Mode",
    "Finance": "Keuangan",
    "Fitness": "Fitness",
    "Food": "Makanan",
    "Food Delivery": "Penghantaran makanan",
    "Food Service": "Perkhidmatan makanan",
    "Food Service Jobs": "Pekerjaan kuliner",
    "Founders": "Pengasas",
    "Freelance": "Freelance",
    "Gadgets": "Gadget",
    "Gaming": "Permainan",
    "Good News": "Berita baik",
    "Government": "Kerajaan",
    "Handmade": "Buatan tangan",
    "Health": "Kesihatan",
    "History": "Sejarah",
    "Home Appliances": "Peralatan rumah",
    "Hotels": "Hotel",
    "Housing": "Perumahan",
    "Humor": "Humor",
    "Incidents": "Insiden",
    "Industry": "Industri",
    "Inspiration": "Inspirasi",
    "Internet": "Internet",
    "Interviews": "Temu bual",
    "Investigations": "Siasatan",
    "Investing": "Investasi",
    "Investment": "Investasi",
    "Irony": "Ironi",
    "Job Learning": "Belajar profesi",
    "Languages": "Bahasa",
    "Logistics": "Logistik",
    "Macroeconomy": "Makroekonomi",
    "Management": "Pengurusan",
    "Marketing": "Marketing",
    "Marketplaces & Shops": "Marketplace & toko",
    "Markets": "Pasar",
    "Matches": "Perlawanan",
    "Medicine": "Perubatan",
    "Memes": "Meme",
    "Misc": "Pelbagai",
    "Mobile Games": "Game mobile",
    "Moto": "Motor",
    "Music": "Muzik",
    "Nature": "Alam semula jadi",
    "New & Trending": "Baru & tren",
    "New Arrivals": "Baru",
    "News": "Berita",
    "No Negative": "Tanpa negatif",
    "Nutrition": "Pemakanan",
    "Opinion": "Pendapat",
    "Other": "Lain-lain",
    "Other Transport": "Transportasi lain",
    "PC": "PC",
    "PC & Components": "PC & komponen",
    "Parenting": "Parenting",
    "Part-time": "Paruh waktu",
    "Payment Systems": "Sistem pembayaran",
    "People": "Orang",
    "Personal Finance": "Keuangan pribadi",
    "Photography": "Fotografi",
    "Plants": "Tumbuhan",
    "Politics": "Politik",
    "Products": "Produk",
    "Psychology": "Psikologi",
    "Real Estate": "Properti",
    "Recipes": "Resep",
    "Regions & Countries": "Wilayah & negara",
    "Relationships": "Hubungan",
    "Remote": "Remote",
    "Research": "Penyelidikan",
    "Restaurants / Cafes / Bars": "Restoran / kafe / bar",
    "Resume": "CV",
    "Reviews": "Ulasan",
    "Routes": "Rute",
    "SMM": "SMM",
    "Satire": "Satire",
    "Science": "Sains",
    "Self-awareness": "Kesadaran diri",
    "Self-development": "Pembangunan diri",
    "Series": "Serial",
    "Shops & Brands": "Toko & merek",
    "Software": "Software",
    "Software & Marketing": "Software & marketing",
    "Space": "Antariksa",
    "Sports": "Sukan",
    "Sports News": "Berita olahraga",
    "Startups": "Startup",
    "Style": "Gaya",
    "TON": "TON",
    "Technology": "Teknologi",
    "Telegram": "Telegram",
    "Trading": "Trading",
    "Training": "Latihan",
    "Transfers": "Transfer",
    "Transport": "Transportasi",
    "Travel": "Perjalanan",
    "Updates": "Pembaruan",
    "Vacancies": "Jawatan kosong",
    "Vacation": "Percutian",
    "War": "Perang",
    "Web & Apps": "Web & aplikasi",
    "Work": "Kerja",
    "World": "Dunia",
    "World Politics": "Politik dunia"
  },
  "in": {
    "AI": "AI",
    "Advertising": "विज्ञापन",
    "Advice": "सलाह",
    "All": "सभी",
    "Analytics": "विश्लेषण",
    "Animals": "जानवर",
    "Art": "कला",
    "Auto": "ऑटो",
    "Banks": "बैंक",
    "Beauty": "सुंदरता",
    "Blogs": "ब्लॉग",
    "Body Shape": "शरीर का आकार",
    "Books": "किताबें",
    "Bots": "बॉट्स",
    "Branding": "ब्रांडिंग",
    "Brands": "ब्रांड",
    "Breaking": "ताज़ा",
    "Business": "बिजनेस",
    "Cases": "केस",
    "Career": "करियर",
    "Celebrities": "सेलेब्रिटी",
    "Championships": "चैंपियनशिप",
    "Channels": "चैनल",
    "Cinema": "सिनेमा",
    "Companies": "कंपनियाँ",
    "Conflicts": "संघर्ष",
    "Console": "कंसोल",
    "Construction": "निर्माण",
    "Construction Equipment": "निर्माण उपकरण",
    "Countries": "देश",
    "Courses": "कोर्स",
    "Creativity": "रचनात्मकता",
    "Crypto": "क्रिप्टो",
    "Culture": "संस्कृति",
    "Delivery": "डिलीवरी",
    "Design": "डिज़ाइन",
    "Development": "डेवलपमेंट",
    "Discoveries": "खोजें",
    "E-commerce": "ई-कॉमर्स",
    "Ecology": "पर्यावरण",
    "Economy": "अर्थव्यवस्था",
    "Education": "शिक्षा",
    "Elections": "चुनाव",
    "Electronics": "इलेक्ट्रॉनिक्स",
    "Energy": "ऊर्जा",
    "Entrepreneurship": "उद्यमिता",
    "Esports": "ई-स्पोर्ट्स",
    "Fashion": "फैशन",
    "Finance": "वित्त",
    "Fitness": "फिटनेस",
    "Food": "खाना",
    "Food Delivery": "खाना डिलीवरी",
    "Food Service": "फूड सर्विस",
    "Food Service Jobs": "फूड सर्विस नौकरियाँ",
    "Founders": "फाउंडर्स",
    "Freelance": "फ्रीलांस",
    "Gadgets": "गैजेट्स",
    "Gaming": "गेमिंग",
    "Good News": "अच्छी खबरें",
    "Government": "सरकार",
    "Handmade": "हैंडमेड",
    "Health": "स्वास्थ्य",
    "History": "इतिहास",
    "Home Appliances": "घरेलू उपकरण",
    "Hotels": "होटल",
    "Housing": "आवास",
    "Humor": "हास्य",
    "Incidents": "घटनाएँ",
    "Industry": "उद्योग",
    "Inspiration": "प्रेरणा",
    "Internet": "इंटरनेट",
    "Interviews": "इंटरव्यू",
    "Investigations": "जांच",
    "Investing": "निवेश",
    "Investment": "निवेश",
    "Irony": "व्यंग्य",
    "Job Learning": "पेशेवर सीख",
    "Languages": "भाषाएँ",
    "Logistics": "लॉजिस्टिक्स",
    "Macroeconomy": "मैक्रोइकॉनॉमी",
    "Management": "प्रबंधन",
    "Marketing": "मार्केटिंग",
    "Marketplaces & Shops": "मार्केटप्लेस और दुकानें",
    "Markets": "बाज़ार",
    "Matches": "मैच",
    "Medicine": "चिकित्सा",
    "Memes": "मीम्स",
    "Misc": "विविध",
    "Mobile Games": "मोबाइल गेम्स",
    "Moto": "मोटो",
    "Music": "संगीत",
    "Nature": "प्रकृति",
    "New & Trending": "नया और ट्रेंडिंग",
    "New Arrivals": "नई चीज़ें",
    "News": "खबरें",
    "No Negative": "नकारात्मक नहीं",
    "Nutrition": "पोषण",
    "Opinion": "राय",
    "Other": "अन्य",
    "Other Transport": "अन्य परिवहन",
    "PC": "PC",
    "PC & Components": "PC और कंपोनेंट्स",
    "Parenting": "पालन-पोषण",
    "Part-time": "पार्ट-टाइम",
    "Payment Systems": "भुगतान सिस्टम",
    "People": "लोग",
    "Personal Finance": "व्यक्तिगत वित्त",
    "Photography": "फोटो",
    "Plants": "पौधे",
    "Politics": "राजनीति",
    "Products": "उत्पाद",
    "Psychology": "मनोविज्ञान",
    "Real Estate": "रियल एस्टेट",
    "Recipes": "रेसिपी",
    "Regions & Countries": "क्षेत्र और देश",
    "Relationships": "रिश्ते",
    "Remote": "रिमोट",
    "Research": "शोध",
    "Restaurants / Cafes / Bars": "रेस्तरां / कैफ़े / बार",
    "Resume": "रिज़्यूमे",
    "Reviews": "समीक्षाएँ",
    "Routes": "रूट",
    "SMM": "SMM",
    "Satire": "व्यंग्य",
    "Science": "विज्ञान",
    "Self-awareness": "आत्म-ज्ञान",
    "Self-development": "आत्म-विकास",
    "Series": "सीरीज़",
    "Shops & Brands": "दुकानें और ब्रांड",
    "Software": "सॉफ्टवेयर",
    "Software & Marketing": "सॉफ्टवेयर और मार्केटिंग",
    "Space": "अंतरिक्ष",
    "Sports": "खेल",
    "Sports News": "खेल समाचार",
    "Startups": "स्टार्टअप्स",
    "Style": "स्टाइल",
    "TON": "TON",
    "Technology": "टेक्नोलॉजी",
    "Telegram": "Telegram",
    "Trading": "ट्रेडिंग",
    "Training": "ट्रेनिंग",
    "Transfers": "ट्रांसफर",
    "Transport": "परिवहन",
    "Travel": "यात्रा",
    "Updates": "अपडेट्स",
    "Vacancies": "नौकरियाँ",
    "Vacation": "छुट्टियाँ",
    "War": "युद्ध",
    "Web & Apps": "वेब और ऐप्स",
    "Work": "काम",
    "World": "दुनिया",
    "World Politics": "विश्व राजनीति"
  },
  "pk": {
    "AI": "AI",
    "Advertising": "اشتہار",
    "Advice": "مشورے",
    "All": "سب",
    "Analytics": "تجزیات",
    "Animals": "جانور",
    "Art": "آرٹ",
    "Auto": "آٹو",
    "Banks": "بینک",
    "Beauty": "خوبصورتی",
    "Blogs": "بلاگز",
    "Body Shape": "جسمانی شکل",
    "Books": "کتابیں",
    "Bots": "بوٹس",
    "Branding": "برانڈنگ",
    "Brands": "برانڈز",
    "Breaking": "فوری",
    "Business": "کاروبار",
    "Cases": "کیسز",
    "Career": "کیریئر",
    "Celebrities": "مشہور شخصیات",
    "Championships": "چیمپئن شپس",
    "Channels": "چینلز",
    "Cinema": "سینما",
    "Companies": "کمپنیاں",
    "Conflicts": "تنازعات",
    "Console": "کنسول",
    "Construction": "تعمیرات",
    "Construction Equipment": "تعمیراتی سامان",
    "Countries": "ممالک",
    "Courses": "کورسز",
    "Creativity": "تخلیقی صلاحیت",
    "Crypto": "کرپٹو",
    "Culture": "ثقافت",
    "Delivery": "ڈیلیوری",
    "Design": "ڈیزائن",
    "Development": "ڈیولپمنٹ",
    "Discoveries": "دریافتیں",
    "E-commerce": "ای کامرس",
    "Ecology": "ماحولیات",
    "Economy": "معیشت",
    "Education": "تعلیم",
    "Elections": "انتخابات",
    "Electronics": "الیکٹرانکس",
    "Energy": "توانائی",
    "Entrepreneurship": "انٹرپرینیورشپ",
    "Esports": "ای اسپورٹس",
    "Fashion": "فیشن",
    "Finance": "مالیات",
    "Fitness": "فٹنس",
    "Food": "کھانا",
    "Food Delivery": "فوڈ ڈیلیوری",
    "Food Service": "فوڈ سروس",
    "Food Service Jobs": "فوڈ سروس نوکریاں",
    "Founders": "فاؤنڈرز",
    "Freelance": "فری لانس",
    "Gadgets": "گیجٹس",
    "Gaming": "گیمنگ",
    "Good News": "اچھی خبریں",
    "Government": "حکومت",
    "Handmade": "ہینڈ میڈ",
    "Health": "صحت",
    "History": "تاریخ",
    "Home Appliances": "گھریلو آلات",
    "Hotels": "ہوٹلز",
    "Housing": "رہائش",
    "Humor": "مزاح",
    "Incidents": "واقعات",
    "Industry": "صنعت",
    "Inspiration": "الہام",
    "Internet": "انٹرنیٹ",
    "Interviews": "انٹرویوز",
    "Investigations": "تحقیقات",
    "Investing": "سرمایہ کاری",
    "Investment": "سرمایہ کاری",
    "Irony": "طنز",
    "Job Learning": "پیشہ ورانہ تعلیم",
    "Languages": "زبانیں",
    "Logistics": "لاجسٹکس",
    "Macroeconomy": "میکرو اکانومی",
    "Management": "انتظام",
    "Marketing": "مارکیٹنگ",
    "Marketplaces & Shops": "مارکیٹ پلیسز اور دکانیں",
    "Markets": "مارکیٹس",
    "Matches": "میچز",
    "Medicine": "طب",
    "Memes": "میمز",
    "Misc": "متفرق",
    "Mobile Games": "موبائل گیمز",
    "Moto": "موٹو",
    "Music": "موسیقی",
    "Nature": "فطرت",
    "New & Trending": "نیا اور ٹرینڈنگ",
    "New Arrivals": "نئی آمد",
    "News": "خبریں",
    "No Negative": "منفی نہیں",
    "Nutrition": "غذائیت",
    "Opinion": "رائے",
    "Other": "دیگر",
    "Other Transport": "دیگر ٹرانسپورٹ",
    "PC": "PC",
    "PC & Components": "PC اور پرزے",
    "Parenting": "والدین",
    "Part-time": "پارٹ ٹائم",
    "Payment Systems": "ادائیگی کے نظام",
    "People": "لوگ",
    "Personal Finance": "ذاتی مالیات",
    "Photography": "فوٹوگرافی",
    "Plants": "پودے",
    "Politics": "سیاست",
    "Products": "مصنوعات",
    "Psychology": "نفسیات",
    "Real Estate": "ریئل اسٹیٹ",
    "Recipes": "ترکیبیں",
    "Regions & Countries": "علاقے اور ممالک",
    "Relationships": "تعلقات",
    "Remote": "ریموٹ",
    "Research": "تحقیق",
    "Restaurants / Cafes / Bars": "ریستوران / کیفے / بارز",
    "Resume": "ریزیومے",
    "Reviews": "جائزے",
    "Routes": "راستے",
    "SMM": "SMM",
    "Satire": "طنز",
    "Science": "سائنس",
    "Self-awareness": "خود آگاہی",
    "Self-development": "خود ترقی",
    "Series": "سیریز",
    "Shops & Brands": "دکانیں اور برانڈز",
    "Software": "سافٹ ویئر",
    "Software & Marketing": "سافٹ ویئر اور مارکیٹنگ",
    "Space": "خلا",
    "Sports": "کھیل",
    "Sports News": "کھیلوں کی خبریں",
    "Startups": "اسٹارٹ اپس",
    "Style": "اسٹائل",
    "TON": "TON",
    "Technology": "ٹیکنالوجی",
    "Telegram": "Telegram",
    "Trading": "ٹریڈنگ",
    "Training": "ٹریننگ",
    "Transfers": "ٹرانسفرز",
    "Transport": "ٹرانسپورٹ",
    "Travel": "سفر",
    "Updates": "اپڈیٹس",
    "Vacancies": "نوکریاں",
    "Vacation": "چھٹیاں",
    "War": "جنگ",
    "Web & Apps": "ویب اور ایپس",
    "Work": "کام",
    "World": "دنیا",
    "World Politics": "عالمی سیاست"
  },
  "ir": {
    "AI": "هوش مصنوعی",
    "Advertising": "تبلیغات",
    "Advice": "نکات",
    "All": "همه",
    "Analytics": "تحلیل",
    "Animals": "حیوانات",
    "Art": "هنر",
    "Auto": "خودرو",
    "Banks": "بانک‌ها",
    "Beauty": "زیبایی",
    "Blogs": "وبلاگ‌ها",
    "Body Shape": "فرم بدن",
    "Books": "کتاب‌ها",
    "Bots": "ربات‌ها",
    "Branding": "برندسازی",
    "Brands": "برندها",
    "Breaking": "فوری",
    "Business": "کسب‌وکار",
    "Cases": "نمونه‌ها",
    "Career": "حرفه",
    "Celebrities": "ستاره‌ها",
    "Championships": "قهرمانی‌ها",
    "Channels": "کانال‌ها",
    "Cinema": "سینما",
    "Companies": "شرکت‌ها",
    "Conflicts": "درگیری‌ها",
    "Console": "کنسول",
    "Construction": "ساخت‌وساز",
    "Construction Equipment": "تجهیزات ساختمانی",
    "Countries": "کشورها",
    "Courses": "دوره‌ها",
    "Creativity": "خلاقیت",
    "Crypto": "کریپتو",
    "Culture": "فرهنگ",
    "Delivery": "تحویل",
    "Design": "طراحی",
    "Development": "توسعه",
    "Discoveries": "کشف‌ها",
    "E-commerce": "تجارت الکترونیک",
    "Ecology": "اکولوژی",
    "Economy": "اقتصاد",
    "Education": "آموزش",
    "Elections": "انتخابات",
    "Electronics": "الکترونیک",
    "Energy": "انرژی",
    "Entrepreneurship": "کارآفرینی",
    "Esports": "ورزش‌های الکترونیک",
    "Fashion": "مد",
    "Finance": "مالی",
    "Fitness": "فیتنس",
    "Food": "غذا",
    "Food Delivery": "تحویل غذا",
    "Food Service": "رستوران‌داری",
    "Food Service Jobs": "کار در رستوران‌داری",
    "Founders": "بنیان‌گذاران",
    "Freelance": "فریلنس",
    "Gadgets": "گجت‌ها",
    "Gaming": "بازی",
    "Good News": "خبرهای خوب",
    "Government": "دولت",
    "Handmade": "دست‌ساز",
    "Health": "سلامت",
    "History": "تاریخ",
    "Home Appliances": "لوازم خانگی",
    "Hotels": "هتل‌ها",
    "Housing": "مسکن",
    "Humor": "طنز",
    "Incidents": "حوادث",
    "Industry": "صنعت",
    "Inspiration": "الهام",
    "Internet": "اینترنت",
    "Interviews": "مصاحبه‌ها",
    "Investigations": "تحقیقات",
    "Investing": "سرمایه‌گذاری",
    "Investment": "سرمایه‌گذاری",
    "Irony": "کنایه",
    "Job Learning": "آموزش شغلی",
    "Languages": "زبان‌ها",
    "Logistics": "لجستیک",
    "Macroeconomy": "اقتصاد کلان",
    "Management": "مدیریت",
    "Marketing": "بازاریابی",
    "Marketplaces & Shops": "مارکت‌پلیس‌ها و فروشگاه‌ها",
    "Markets": "بازارها",
    "Matches": "مسابقات",
    "Medicine": "پزشکی",
    "Memes": "میم‌ها",
    "Misc": "متفرقه",
    "Mobile Games": "بازی‌های موبایل",
    "Moto": "موتو",
    "Music": "موسیقی",
    "Nature": "طبیعت",
    "New & Trending": "جدید و ترند",
    "New Arrivals": "تازه‌ها",
    "News": "اخبار",
    "No Negative": "بدون منفی",
    "Nutrition": "تغذیه",
    "Opinion": "نظرات",
    "Other": "دیگر",
    "Other Transport": "حمل‌ونقل دیگر",
    "PC": "PC",
    "PC & Components": "PC و قطعات",
    "Parenting": "والدگری",
    "Part-time": "پاره‌وقت",
    "Payment Systems": "سیستم‌های پرداخت",
    "People": "مردم",
    "Personal Finance": "مالی شخصی",
    "Photography": "عکاسی",
    "Plants": "گیاهان",
    "Politics": "سیاست",
    "Products": "محصولات",
    "Psychology": "روان‌شناسی",
    "Real Estate": "املاک",
    "Recipes": "دستور غذا",
    "Regions & Countries": "مناطق و کشورها",
    "Relationships": "روابط",
    "Remote": "دورکاری",
    "Research": "پژوهش",
    "Restaurants / Cafes / Bars": "رستوران‌ها / کافه‌ها / بارها",
    "Resume": "رزومه",
    "Reviews": "نقد و بررسی",
    "Routes": "مسیرها",
    "SMM": "SMM",
    "Satire": "هجو",
    "Science": "علم",
    "Self-awareness": "خودشناسی",
    "Self-development": "خودتوسعه",
    "Series": "سریال‌ها",
    "Shops & Brands": "فروشگاه‌ها و برندها",
    "Software": "نرم‌افزار",
    "Software & Marketing": "نرم‌افزار و بازاریابی",
    "Space": "فضا",
    "Sports": "ورزش",
    "Sports News": "اخبار ورزشی",
    "Startups": "استارتاپ‌ها",
    "Style": "استایل",
    "TON": "TON",
    "Technology": "فناوری",
    "Telegram": "Telegram",
    "Trading": "ترید",
    "Training": "تمرین",
    "Transfers": "انتقالات",
    "Transport": "حمل‌ونقل",
    "Travel": "سفر",
    "Updates": "به‌روزرسانی‌ها",
    "Vacancies": "فرصت‌های شغلی",
    "Vacation": "تعطیلات",
    "War": "جنگ",
    "Web & Apps": "وب و اپلیکیشن‌ها",
    "Work": "کار",
    "World": "جهان",
    "World Politics": "سیاست جهان"
  },
  "ae": {
    "AI": "ذكاء اصطناعي",
    "Advertising": "إعلانات",
    "Advice": "نصائح",
    "All": "الكل",
    "Analytics": "تحليلات",
    "Animals": "حيوانات",
    "Art": "فن",
    "Auto": "سيارات",
    "Banks": "بنوك",
    "Beauty": "جمال",
    "Blogs": "مدونات",
    "Body Shape": "شكل الجسم",
    "Books": "كتب",
    "Bots": "بوتات",
    "Branding": "بناء العلامة",
    "Brands": "علامات تجارية",
    "Breaking": "عاجل",
    "Business": "أعمال",
    "Cases": "حالات",
    "Career": "مسار مهني",
    "Celebrities": "مشاهير",
    "Championships": "بطولات",
    "Channels": "قنوات",
    "Cinema": "سينما",
    "Companies": "شركات",
    "Conflicts": "نزاعات",
    "Console": "منصات ألعاب",
    "Construction": "بناء",
    "Construction Equipment": "معدات بناء",
    "Countries": "دول",
    "Courses": "دورات",
    "Creativity": "إبداع",
    "Crypto": "كريبتو",
    "Culture": "ثقافة",
    "Delivery": "توصيل",
    "Design": "تصميم",
    "Development": "تطوير",
    "Discoveries": "اكتشافات",
    "E-commerce": "تجارة إلكترونية",
    "Ecology": "بيئة",
    "Economy": "اقتصاد",
    "Education": "تعليم",
    "Elections": "انتخابات",
    "Electronics": "إلكترونيات",
    "Energy": "طاقة",
    "Entrepreneurship": "ريادة أعمال",
    "Esports": "رياضات إلكترونية",
    "Fashion": "موضة",
    "Finance": "مال وأعمال",
    "Fitness": "لياقة",
    "Food": "طعام",
    "Food Delivery": "توصيل الطعام",
    "Food Service": "مطاعم ومقاهٍ",
    "Food Service Jobs": "وظائف المطاعم",
    "Founders": "مؤسسون",
    "Freelance": "عمل حر",
    "Gadgets": "أجهزة",
    "Gaming": "ألعاب",
    "Good News": "أخبار جيدة",
    "Government": "حكومة",
    "Handmade": "يدوي",
    "Health": "صحة",
    "History": "تاريخ",
    "Home Appliances": "أجهزة منزلية",
    "Hotels": "فنادق",
    "Housing": "سكن",
    "Humor": "فكاهة",
    "Incidents": "حوادث",
    "Industry": "صناعة",
    "Inspiration": "إلهام",
    "Internet": "إنترنت",
    "Interviews": "مقابلات",
    "Investigations": "تحقيقات",
    "Investing": "استثمار",
    "Investment": "استثمار",
    "Irony": "سخرية",
    "Job Learning": "تعلم المهنة",
    "Languages": "لغات",
    "Logistics": "لوجستيات",
    "Macroeconomy": "اقتصاد كلي",
    "Management": "إدارة",
    "Marketing": "تسويق",
    "Marketplaces & Shops": "منصات ومتاجر",
    "Markets": "أسواق",
    "Matches": "مباريات",
    "Medicine": "طب",
    "Memes": "ميمز",
    "Misc": "متنوع",
    "Mobile Games": "ألعاب الجوال",
    "Moto": "دراجات نارية",
    "Music": "موسيقى",
    "Nature": "طبيعة",
    "New & Trending": "جديد ورائج",
    "New Arrivals": "وصل حديثًا",
    "News": "أخبار",
    "No Negative": "بدون سلبية",
    "Nutrition": "تغذية",
    "Opinion": "آراء",
    "Other": "أخرى",
    "Other Transport": "نقل آخر",
    "PC": "PC",
    "PC & Components": "كمبيوتر ومكونات",
    "Parenting": "تربية الأطفال",
    "Part-time": "دوام جزئي",
    "Payment Systems": "أنظمة الدفع",
    "People": "أشخاص",
    "Personal Finance": "تمويل شخصي",
    "Photography": "تصوير",
    "Plants": "نباتات",
    "Politics": "سياسة",
    "Products": "منتجات",
    "Psychology": "علم النفس",
    "Real Estate": "عقارات",
    "Recipes": "وصفات",
    "Regions & Countries": "مناطق ودول",
    "Relationships": "علاقات",
    "Remote": "عن بعد",
    "Research": "أبحاث",
    "Restaurants / Cafes / Bars": "مطاعم / مقاهٍ / بارات",
    "Resume": "سيرة ذاتية",
    "Reviews": "مراجعات",
    "Routes": "مسارات",
    "SMM": "SMM",
    "Satire": "هجاء",
    "Science": "علم",
    "Self-awareness": "معرفة الذات",
    "Self-development": "تطوير الذات",
    "Series": "مسلسلات",
    "Shops & Brands": "متاجر وعلامات",
    "Software": "برمجيات",
    "Software & Marketing": "برمجيات وتسويق",
    "Space": "فضاء",
    "Sports": "رياضة",
    "Sports News": "أخبار الرياضة",
    "Startups": "شركات ناشئة",
    "Style": "أسلوب",
    "TON": "TON",
    "Technology": "تكنولوجيا",
    "Telegram": "Telegram",
    "Trading": "تداول",
    "Training": "تدريب",
    "Transfers": "انتقالات",
    "Transport": "نقل",
    "Travel": "سفر",
    "Updates": "تحديثات",
    "Vacancies": "وظائف شاغرة",
    "Vacation": "إجازة",
    "War": "حرب",
    "Web & Apps": "ويب وتطبيقات",
    "Work": "عمل",
    "World": "العالم",
    "World Politics": "سياسة عالمية"
  },
  "kz": {
    "AI": "AI",
    "Advertising": "Жарнама",
    "Advice": "Кеңестер",
    "All": "Барлығы",
    "Analytics": "Аналитика",
    "Animals": "Жануарлар",
    "Art": "Өнер",
    "Auto": "Авто",
    "Banks": "Банктер",
    "Beauty": "Сұлулық",
    "Blogs": "Блогтар",
    "Body Shape": "Дене пішіні",
    "Books": "Кітаптар",
    "Bots": "Боттар",
    "Branding": "Брендинг",
    "Brands": "Брендтер",
    "Breaking": "Шұғыл",
    "Business": "Бизнес",
    "Cases": "Кейстер",
    "Career": "Мансап",
    "Celebrities": "Жұлдыздар",
    "Championships": "Чемпионаттар",
    "Channels": "Арналар",
    "Cinema": "Кино",
    "Companies": "Компаниялар",
    "Conflicts": "Қақтығыстар",
    "Console": "Консольдер",
    "Construction": "Құрылыс",
    "Construction Equipment": "Құрылыс техникасы",
    "Countries": "Елдер",
    "Courses": "Курстар",
    "Creativity": "Шығармашылық",
    "Crypto": "Крипто",
    "Culture": "Мәдениет",
    "Delivery": "Жеткізу",
    "Design": "Дизайн",
    "Development": "Әзірлеу",
    "Discoveries": "Ашылымдар",
    "E-commerce": "E-commerce",
    "Ecology": "Экология",
    "Economy": "Экономика",
    "Education": "Білім",
    "Elections": "Сайлау",
    "Electronics": "Электроника",
    "Energy": "Энергетика",
    "Entrepreneurship": "Кәсіпкерлік",
    "Esports": "Киберспорт",
    "Fashion": "Сән",
    "Finance": "Қаржы",
    "Fitness": "Фитнес",
    "Food": "Тағам",
    "Food Delivery": "Тағам жеткізу",
    "Food Service": "Қоғамдық тамақтану",
    "Food Service Jobs": "Қоғамдық тамақтану жұмысы",
    "Founders": "Фаундерлер",
    "Freelance": "Фриланс",
    "Gadgets": "Гаджеттер",
    "Gaming": "Ойындар",
    "Good News": "Жақсы жаңалықтар",
    "Government": "Билік",
    "Handmade": "Қолөнер",
    "Health": "Денсаулық",
    "History": "Тарих",
    "Home Appliances": "Тұрмыстық техника",
    "Hotels": "Қонақүйлер",
    "Housing": "Тұрғын үй",
    "Humor": "Әзіл",
    "Incidents": "Оқиғалар",
    "Industry": "Өнеркәсіп",
    "Inspiration": "Шабыт",
    "Internet": "Интернет",
    "Interviews": "Сұхбаттар",
    "Investigations": "Зерттеулер",
    "Investing": "Инвестициялар",
    "Investment": "Инвестиция",
    "Irony": "Ирония",
    "Job Learning": "Кәсіп оқу",
    "Languages": "Тілдер",
    "Logistics": "Логистика",
    "Macroeconomy": "Макроэкономика",
    "Management": "Басқару",
    "Marketing": "Маркетинг",
    "Marketplaces & Shops": "Маркетплейстер мен дүкендер",
    "Markets": "Нарықтар",
    "Matches": "Матчтар",
    "Medicine": "Медицина",
    "Memes": "Мемдер",
    "Misc": "Әртүрлі",
    "Mobile Games": "Мобильді ойындар",
    "Moto": "Мото",
    "Music": "Музыка",
    "Nature": "Табиғат",
    "New & Trending": "Жаңалар мен трендтер",
    "New Arrivals": "Жаңалар",
    "News": "Жаңалықтар",
    "No Negative": "Негативсіз",
    "Nutrition": "Тамақтану",
    "Opinion": "Пікірлер",
    "Other": "Басқа",
    "Other Transport": "Басқа көлік",
    "PC": "PC",
    "PC & Components": "PC және бөлшектер",
    "Parenting": "Ата-ана",
    "Part-time": "Қосымша жұмыс",
    "Payment Systems": "Төлем жүйелері",
    "People": "Адамдар",
    "Personal Finance": "Жеке қаржы",
    "Photography": "Фото",
    "Plants": "Өсімдіктер",
    "Politics": "Саясат",
    "Products": "Өнімдер",
    "Psychology": "Психология",
    "Real Estate": "Жылжымайтын мүлік",
    "Recipes": "Рецепттер",
    "Regions & Countries": "Аймақтар мен елдер",
    "Relationships": "Қарым-қатынас",
    "Remote": "Қашықтан",
    "Research": "Зерттеу",
    "Restaurants / Cafes / Bars": "Мейрамханалар / кафелер / барлар",
    "Resume": "Түйіндеме",
    "Reviews": "Пікірлер",
    "Routes": "Маршруттар",
    "SMM": "SMM",
    "Satire": "Сатира",
    "Science": "Ғылым",
    "Self-awareness": "Өзін тану",
    "Self-development": "Өзін дамыту",
    "Series": "Сериалдар",
    "Shops & Brands": "Дүкендер мен брендтер",
    "Software": "Софт",
    "Software & Marketing": "Софт және маркетинг",
    "Space": "Ғарыш",
    "Sports": "Спорт",
    "Sports News": "Спорт жаңалықтары",
    "Startups": "Стартаптар",
    "Style": "Стиль",
    "TON": "TON",
    "Technology": "Технологиялар",
    "Telegram": "Telegram",
    "Trading": "Трейдинг",
    "Training": "Жаттығулар",
    "Transfers": "Трансферлер",
    "Transport": "Көлік",
    "Travel": "Саяхат",
    "Updates": "Жаңартулар",
    "Vacancies": "Вакансиялар",
    "Vacation": "Демалыс",
    "War": "Соғыс",
    "Web & Apps": "Сайттар мен қолданбалар",
    "Work": "Жұмыс",
    "World": "Әлем",
    "World Politics": "Әлемдік саясат"
  },
  "uz": {
    "AI": "AI",
    "Advertising": "Reklama",
    "Advice": "Maslahatlar",
    "All": "Hammasi",
    "Analytics": "Analitika",
    "Animals": "Hayvonlar",
    "Art": "San’at",
    "Auto": "Avto",
    "Banks": "Banklar",
    "Beauty": "Go‘zallik",
    "Blogs": "Bloglar",
    "Body Shape": "Tana shakli",
    "Books": "Kitoblar",
    "Bots": "Botlar",
    "Branding": "Brending",
    "Brands": "Brendlar",
    "Breaking": "Shoshilinch",
    "Business": "Biznes",
    "Cases": "Keyslar",
    "Career": "Karyera",
    "Celebrities": "Mashhurlar",
    "Championships": "Chempionatlar",
    "Channels": "Kanallar",
    "Cinema": "Kino",
    "Companies": "Kompaniyalar",
    "Conflicts": "Mojarolar",
    "Console": "Konsollar",
    "Construction": "Qurilish",
    "Construction Equipment": "Qurilish texnikasi",
    "Countries": "Mamlakatlar",
    "Courses": "Kurslar",
    "Creativity": "Ijod",
    "Crypto": "Kripto",
    "Culture": "Madaniyat",
    "Delivery": "Yetkazib berish",
    "Design": "Dizayn",
    "Development": "Dasturlash",
    "Discoveries": "Kashfiyotlar",
    "E-commerce": "E-commerce",
    "Ecology": "Ekologiya",
    "Economy": "Iqtisodiyot",
    "Education": "Ta’lim",
    "Elections": "Saylovlar",
    "Electronics": "Elektronika",
    "Energy": "Energetika",
    "Entrepreneurship": "Tadbirkorlik",
    "Esports": "Kibersport",
    "Fashion": "Moda",
    "Finance": "Moliya",
    "Fitness": "Fitnes",
    "Food": "Ovqat",
    "Food Delivery": "Ovqat yetkazish",
    "Food Service": "Umumiy ovqatlanish",
    "Food Service Jobs": "Ovqatlanish sohasida ish",
    "Founders": "Faunderlar",
    "Freelance": "Frilans",
    "Gadgets": "Gadjetlar",
    "Gaming": "O‘yinlar",
    "Good News": "Yaxshi yangiliklar",
    "Government": "Hokimiyat",
    "Handmade": "Qo‘l mehnati",
    "Health": "Sog‘liq",
    "History": "Tarix",
    "Home Appliances": "Maishiy texnika",
    "Hotels": "Mehmonxonalar",
    "Housing": "Uy-joy",
    "Humor": "Hazil",
    "Incidents": "Hodisalar",
    "Industry": "Sanoat",
    "Inspiration": "Ilhom",
    "Internet": "Internet",
    "Interviews": "Intervyular",
    "Investigations": "Surishtiruvlar",
    "Investing": "Investitsiyalar",
    "Investment": "Investitsiya",
    "Irony": "Kinoya",
    "Job Learning": "Kasb o‘rganish",
    "Languages": "Tillar",
    "Logistics": "Logistika",
    "Macroeconomy": "Makroiqtisodiyot",
    "Management": "Boshqaruv",
    "Marketing": "Marketing",
    "Marketplaces & Shops": "Marketpleyslar va do‘konlar",
    "Markets": "Bozorlar",
    "Matches": "Uchrashuvlar",
    "Medicine": "Tibbiyot",
    "Memes": "Memlar",
    "Misc": "Turli",
    "Mobile Games": "Mobil o‘yinlar",
    "Moto": "Moto",
    "Music": "Musiqa",
    "Nature": "Tabiat",
    "New & Trending": "Yangi va trendlar",
    "New Arrivals": "Yangiliklar",
    "News": "Yangiliklar",
    "No Negative": "Negativsiz",
    "Nutrition": "Ovqatlanish",
    "Opinion": "Fikrlar",
    "Other": "Boshqa",
    "Other Transport": "Boshqa transport",
    "PC": "PC",
    "PC & Components": "PC va qismlar",
    "Parenting": "Ota-onalik",
    "Part-time": "Qo‘shimcha ish",
    "Payment Systems": "To‘lov tizimlari",
    "People": "Odamlar",
    "Personal Finance": "Shaxsiy moliya",
    "Photography": "Foto",
    "Plants": "O‘simliklar",
    "Politics": "Siyosat",
    "Products": "Mahsulotlar",
    "Psychology": "Psixologiya",
    "Real Estate": "Ko‘chmas mulk",
    "Recipes": "Retseptlar",
    "Regions & Countries": "Hududlar va mamlakatlar",
    "Relationships": "Munosabatlar",
    "Remote": "Masofaviy",
    "Research": "Tadqiqot",
    "Restaurants / Cafes / Bars": "Restoranlar / kafelar / barlar",
    "Resume": "Rezyume",
    "Reviews": "Sharhlar",
    "Routes": "Yo‘nalishlar",
    "SMM": "SMM",
    "Satire": "Satira",
    "Science": "Fan",
    "Self-awareness": "O‘zini anglash",
    "Self-development": "O‘zini rivojlantirish",
    "Series": "Seriallar",
    "Shops & Brands": "Do‘konlar va brendlar",
    "Software": "Soft",
    "Software & Marketing": "Soft va marketing",
    "Space": "Kosmos",
    "Sports": "Sport",
    "Sports News": "Sport yangiliklari",
    "Startups": "Startaplar",
    "Style": "Uslub",
    "TON": "TON",
    "Technology": "Texnologiyalar",
    "Telegram": "Telegram",
    "Trading": "Treydeing",
    "Training": "Mashg‘ulotlar",
    "Transfers": "Transferlar",
    "Transport": "Transport",
    "Travel": "Sayohat",
    "Updates": "Yangilanishlar",
    "Vacancies": "Vakansiyalar",
    "Vacation": "Dam olish",
    "War": "Urush",
    "Web & Apps": "Veb va ilovalar",
    "Work": "Ish",
    "World": "Dunyo",
    "World Politics": "Jahon siyosati"
  }
};

const TAG_LABEL_LOCALE_SOURCE: Partial<Record<SiteLocale, SiteLocale>> = {
  mx: "es",
  ar: "es",
  co: "es",
  ae: "ae",
  eg: "ae",
  sa: "ae",
  za: "us",
  ng: "us",
};

function translatedLabel(locale: SiteLocale, fallback: string) {
  const source = TAG_LABEL_LOCALE_SOURCE[locale] ?? locale;
  return TAG_LABEL_TRANSLATIONS[source]?.[fallback] ?? fallback;
}

function labels(ru: string, en?: string): TagLabelMap {
  const fallback = (en || ru).trim();

  return {
    ru,
    ua: translatedLabel("ua", fallback),
    us: fallback,
    in: translatedLabel("in", fallback),
    ir: translatedLabel("ir", fallback),
    tr: translatedLabel("tr", fallback),
    br: translatedLabel("br", fallback),
    kz: translatedLabel("kz", fallback),
    uz: translatedLabel("uz", fallback),
    ae: translatedLabel("ae", fallback),
    eg: translatedLabel("eg", fallback),
    pk: translatedLabel("pk", fallback),
    id: translatedLabel("id", fallback),
    mx: translatedLabel("mx", fallback),
    sa: translatedLabel("sa", fallback),
    es: translatedLabel("es", fallback),
    it: translatedLabel("it", fallback),
    fr: translatedLabel("fr", fallback),
    de: translatedLabel("de", fallback),
    ar: translatedLabel("ar", fallback),
    co: translatedLabel("co", fallback),
    za: fallback,
    ng: fallback,
    cn: translatedLabel("cn", fallback),
    my: translatedLabel("my", fallback),
  };
}


function tag(value: string, emoji: string, ru: string, en?: string): SiteTag {
  return {
    value,
    emoji,
    labels: labels(ru, en),
  };
}


/**
 * Новая структура taxonomy v2.
 * Её мы будем подключать в UI следующим этапом:
 * - родительские теги
 * - раскрывающиеся подтеги
 * - родитель + подтеги в карточке
 */
export const SITE_TAG_GROUPS: SiteTagGroup[] = [
  {
    ...tag("news", "📰", "Новости", "News"),
    children: [
      tag("news_all", "📰", "Все", "All"),
      tag("news_world", "🌍", "Мир", "World"),
      tag("news_breaking", "⚡", "Срочно", "Breaking"),
      tag("news_regions", "🗺️", "Регионы и страны", "Regions & Countries"),
      tag("news_incidents", "🚨", "Происшествия", "Incidents"),
      tag("news_investigations", "🕵️", "Расследования", "Investigations"),
      tag("news_good", "💛", "Добрые", "Good News"),
      tag("news_no_negative", "🕊️", "Без негатива", "No Negative"),
    ],
  },
  {
    ...tag("politics", "🏛️", "Политика", "Politics"),
    children: [
      tag("politics_all", "🏛️", "Все", "All"),
      tag("politics_world", "🌍", "Мировая", "World Politics"),
      tag("politics_government", "🏢", "Власть", "Government"),
      tag("politics_elections", "🗳️", "Выборы", "Elections"),
      tag("politics_conflicts", "⚔️", "Конфликты", "Conflicts"),
      tag("war", "🔥", "Война", "War"),
      tag("politics_opinion", "🧠", "Мнения", "Opinion"),
      tag("politics_other", "☝️", "Другое", "Other"),
    ],
  },
  {
    ...tag("economy", "📈", "Экономика", "Economy"),
    children: [
      tag("economy_all", "📈", "Все", "All"),
      tag("economy_macro", "🌐", "Макроэкономика", "Macroeconomy"),
      tag("economy_markets", "📊", "Рынки", "Markets"),
      tag("economy_industry", "🏭", "Промышленность", "Industry"),
      tag("economy_energy", "⚡", "Энергетика", "Energy"),
      tag("economy_logistics", "🚚", "Логистика", "Logistics"),
      tag("economy_other", "☝️", "Другое", "Other"),
    ],
  },
  {
    ...tag("business", "💼", "Бизнес", "Business"),
    children: [
      tag("business_all", "💼", "Все", "All"),
      tag("business_companies", "🏢", "Компании", "Companies"),
      tag("business_entrepreneurship", "🧑‍💼", "Предпринимательство", "Entrepreneurship"),
      tag("business_ecommerce", "🛒", "E-commerce", "E-commerce"),
      tag("business_management", "📋", "Управление", "Management"),
      tag("business_cases", "📚", "Кейсы", "Cases"),
      tag("business_other", "☝️", "Другое", "Other"),
    ],
  },
  {
    ...tag("marketplaces", "🌌", "Маркетплейсы и магазины", "Marketplaces & Shops"),
    children: [],
  },
  {
    ...tag("finance", "💰", "Финансы", "Finance"),
    children: [
      tag("finance_all", "💰", "Все", "All"),
      tag("finance_banks", "🏦", "Банки", "Banks"),
      tag("finance_payment_systems", "💱", "Платёжные системы", "Payment Systems"),
      tag("finance_investing", "📈", "Инвестиции", "Investing"),
      tag("finance_trading", "📉", "Трейдинг", "Trading"),
      tag("finance_personal", "💳", "Личные финансы", "Personal Finance"),
      tag("crypto", "₿", "Крипта", "Crypto"),
      tag("finance_other", "☝️", "Другое", "Other"),
    ],
  },
  {
    ...tag("electronics", "🔌", "Электроника", "Electronics"),
    children: [
      tag("electronics_home_appliances", "🏠", "Бытовая техника", "Home Appliances"),
      tag("electronics_pc", "🖥️", "ПК и комплектующие", "PC & Components"),
      tag("electronics_construction", "🛠️", "Строительная", "Construction Equipment"),
      tag("electronics_trends", "✨", "Новинки и тренды", "New & Trending"),
      tag("electronics_brands", "🏷️", "Магазины и бренды", "Shops & Brands"),
      tag("electronics_delivery", "🚚", "Доставка", "Delivery"),
      tag("electronics_reviews", "🧾", "Отзывы", "Reviews"),
    ],
  },
  {
    ...tag("technology", "💻", "Технологии", "Technology"),
    children: [
      tag("technology_all", "💻", "Все", "All"),
      tag("technology_software", "🖥️", "Софт", "Software"),
      tag("technology_dev", "🧑‍💻", "Разработка", "Development"),
      tag("technology_web", "🌐", "Сайты и приложения", "Web & Apps"),
      tag("internet", "🌍", "Интернет", "Internet"),
      tag("gadgets", "📱", "Гаджеты", "Gadgets"),
      tag("ai", "🤖", "AI", "AI"),
      tag("technology_other", "☝️", "Другое", "Other"),
    ],
  },
  {
    ...tag("science", "🔬", "Наука", "Science"),
    children: [
      tag("science_all", "🔬", "Все", "All"),
      tag("science_research", "🧪", "Исследования", "Research"),
      tag("science_discoveries", "✨", "Открытия", "Discoveries"),
      tag("science_medicine", "🩺", "Медицина", "Medicine"),
      tag("space", "🚀", "Космос", "Space"),
      tag("science_other", "☝️", "Другое", "Other"),
    ],
  },
  {
    ...tag("education", "📚", "Образование", "Education"),
    children: [
      tag("education_all", "📚", "Все", "All"),
      tag("education_courses", "🎓", "Курсы", "Courses"),
      tag("education_languages", "🗣️", "Языки", "Languages"),
      tag("education_self", "📘", "Саморазвитие", "Self-development"),
      tag("history", "🏺", "История", "History"),
      tag("books", "📖", "Книги", "Books"),
      tag("education_other", "☝️", "Другое", "Other"),
    ],
  },
  {
    ...tag("culture", "🎭", "Культура", "Culture"),
    children: [
      tag("culture_all", "🎭", "Все", "All"),
      tag("art", "🎨", "Арт", "Art"),
      tag("design", "🧩", "Дизайн", "Design"),
      tag("photography", "📷", "Фото", "Photography"),
      tag("cinema", "🎬", "Кино", "Cinema"),
      tag("series", "📺", "Сериалы", "Series"),
      tag("music", "🎵", "Музыка", "Music"),
      tag("culture_other", "☝️", "Другое", "Other"),
    ],
  },
  {
    ...tag("gaming", "🎮", "Игры", "Gaming"),
    children: [
      tag("gaming_all", "🎮", "Все", "All"),
      tag("gaming_mobile", "📱", "Мобильные", "Mobile Games"),
      tag("gaming_pc", "🖥️", "PC", "PC"),
      tag("gaming_console", "🕹️", "Консоли", "Console"),
      tag("gaming_esports", "🏆", "Киберспорт", "Esports"),
      tag("gaming_other", "☝️", "Другое", "Other"),
    ],
  },
  {
    ...tag("humor", "😁", "Юмор", "Humor"),
    children: [
      tag("humor_all", "🤣", "Все", "All"),
      tag("memes", "😂", "Мемы", "Memes"),
      tag("humor_ironical", "😏", "Ирония", "Irony"),
      tag("humor_satire", "🎭", "Сатира", "Satire"),
      tag("humor_other", "☝️", "Другое", "Other"),
    ],
  },
  {
    ...tag("sports", "⚽", "Спорт", "Sports"),
    children: [
      tag("sports_all", "⚽", "Все", "All"),
      tag("sports_championships", "🏆", "Чемпионаты", "Championships"),
      tag("sports_matches", "🎯", "Матчи", "Matches"),
      tag("sports_news", "📰", "Новости", "Sports News"),
      tag("sports_people", "🧑", "Люди", "People"),
      tag("sports_transfers", "🔁", "Трансферы", "Transfers"),
      tag("sports_analytics", "📊", "Аналитика", "Analytics"),
      tag("sports_other", "☝️", "Другое", "Other"),
    ],
  },
  {
    ...tag("fitness", "🏋️", "Фитнес", "Fitness"),
    children: [
      tag("fitness_all", "🏋️", "Все", "All"),
      tag("fitness_training", "💪", "Тренировки", "Training"),
      tag("fitness_nutrition", "🥗", "Питание", "Nutrition"),
      tag("fitness_body", "🧍", "Форма тела", "Body Shape"),
      tag("fitness_other", "☝️", "Другое", "Other"),
    ],
  },
  {
    ...tag("health", "🩺", "Здоровье", "Health"),
    children: [
      tag("health_all", "🩺", "Все", "All"),
      tag("health_medicine", "💊", "Медицина", "Medicine"),
      tag("health_research", "🔬", "Исследования", "Research"),
      tag("health_food", "🥗", "Питание", "Nutrition"),
      tag("health_advice", "🧠", "Советы", "Advice"),
      tag("health_other", "☝️", "Другое", "Other"),
    ],
  },
  {
    ...tag("travel", "🧳", "Путешествия", "Travel"),
    children: [
      tag("travel_all", "🧳", "Все", "All"),
      tag("travel_rest", "🏖️", "Отдых", "Vacation"),
      tag("travel_countries", "🌍", "Страны", "Countries"),
      tag("travel_routes", "🗺️", "Маршруты", "Routes"),
      tag("travel_hotels", "🏨", "Отели", "Hotels"),
      tag("travel_other", "☝️", "Другое", "Other"),
    ],
  },
  {
    ...tag("food", "🍕", "Еда", "Food"),
    children: [
      tag("food_all", "🍔", "Все", "All"),
      tag("recipes", "🍳", "Рецепты", "Recipes"),
      tag("food_products", "🛒", "Продукты", "Products"),
      tag("food_other", "☝️", "Другое", "Other"),
    ],
  },
  {
    ...tag("food_service", "🍜", "Общепит", "Food Service"),
    children: [
      tag("food_service_places", "🍽️", "Рестораны / кафе / бары", "Restaurants / Cafes / Bars"),
      tag("food_service_delivery", "🛵", "Доставка еды", "Food Delivery"),
      tag("food_service_new", "✨", "Новинки", "New Arrivals"),
      tag("food_service_jobs", "👨‍🍳", "Работа в общепите", "Food Service Jobs"),
      tag("food_service_software", "💻", "Софт и продвижение", "Software & Marketing"),
      tag("food_service_reviews", "🧾", "Отзывы", "Reviews"),
    ],
  },
  {
    ...tag("psychology", "🧠", "Психология", "Psychology"),
    children: [
      tag("psychology_all", "🧠", "Все", "All"),
      tag("psychology_self", "🪞", "Самопознание", "Self-awareness"),
      tag("relationships", "❤️", "Отношения", "Relationships"),
      tag("parenting", "👨‍👩‍👦", "Родительство", "Parenting"),
      tag("psychology_other", "☝️", "Другое", "Other"),
    ],
  },
  {
    ...tag("fashion", "👗", "Мода", "Fashion"),
    children: [
      tag("fashion_all", "👗", "Все", "All"),
      tag("beauty", "💄", "Красота", "Beauty"),
      tag("fashion_style", "✨", "Стиль", "Style"),
      tag("fashion_brands", "👜", "Бренды", "Brands"),
      tag("fashion_other", "☝️", "Другое", "Other"),
    ],
  },
  {
    ...tag("nature", "🌿", "Природа", "Nature"),
    children: [
      tag("nature_all", "🌿", "Все", "All"),
      tag("animals", "🐾", "Животные", "Animals"),
      tag("nature_ecology", "♻️", "Экология", "Ecology"),
      tag("nature_plants", "🌱", "Растения", "Plants"),
      tag("nature_other", "☝️", "Другое", "Other"),
    ],
  },
  {
    ...tag("people", "🧑", "Люди", "People"),
    children: [
      tag("people_all", "🧑", "Все", "All"),
      tag("people_blogs", "✍️", "Блоги", "Blogs"),
      tag("celebrities", "⭐", "Звёзды", "Celebrities"),
      tag("people_interviews", "🎤", "Интервью", "Interviews"),
      tag("people_other", "☝️", "Другое", "Other"),
    ],
  },
  {
    ...tag("marketing", "📣", "Маркетинг", "Marketing"),
    children: [
      tag("marketing_all", "📣", "Все", "All"),
      tag("marketing_smm", "📱", "SMM", "SMM"),
      tag("marketing_ads", "📢", "Реклама", "Advertising"),
      tag("marketing_brand", "🏷️", "Брендинг", "Branding"),
      tag("marketing_other", "☝️", "Другое", "Other"),
    ],
  },
  {
    ...tag("startups", "🧪", "Стартапы", "Startups"),
    children: [
      tag("startups_all", "🧪", "Все", "All"),
      tag("startups_cases", "📚", "Кейсы", "Cases"),
      tag("startups_founders", "🧑‍💼", "Фаундеры", "Founders"),
      tag("startups_invest", "💸", "Инвестиции", "Investment"),
      tag("startups_other", "☝️", "Другое", "Other"),
    ],
  },
  {
    ...tag("jobs", "🛠️", "Работа", "Work"),
    children: [
      tag("jobs_all", "🛠️", "Все", "All"),
      tag("jobs_vacancies", "📄", "Вакансии", "Vacancies"),
      tag("jobs_remote", "🏠", "Удалёнка", "Remote"),
      tag("jobs_parttime", "⏰", "Подработка", "Part-time"),
      tag("jobs_career", "📈", "Карьера", "Career"),
      tag("jobs_freelance", "💻", "Фриланс", "Freelance"),
      tag("jobs_resume", "📝", "Резюме", "Resume"),
      tag("jobs_interviews", "🎤", "Интервью", "Interviews"),
      tag("jobs_learning", "🎓", "Обучение профессии", "Job Learning"),
      tag("jobs_other", "☝️", "Другое", "Other"),
    ],
  },
  {
    ...tag("real_estate", "🏠", "Недвижимость", "Real Estate"),
    children: [
      tag("real_estate_all", "🏠", "Все", "All"),
      tag("real_estate_housing", "🏡", "Жильё", "Housing"),
      tag("real_estate_invest", "💼", "Инвестиции", "Investment"),
      tag("real_estate_build", "🧱", "Стройка и материалы", "Construction"),
      tag("real_estate_other", "☝️", "Другое", "Other"),
    ],
  },
  {
    ...tag("auto", "🚙", "Транспорт", "Transport"),
    children: [
      tag("transport_auto", "🚗", "Авто", "Auto"),
      tag("transport_moto", "🏍️", "Мото", "Moto"),
      tag("transport_other", "🚚", "Другой транспорт", "Other Transport"),
      tag("transport_reviews", "🧾", "Обзоры", "Reviews"),
      tag("transport_other2", "☝️", "Другое", "Other"),
    ],
  },
  {
    ...tag("telegram", "✈️", "Telegram", "Telegram"),
    children: [
      tag("telegram_all", "✈️", "Все", "All"),
      tag("telegram_channels", "📣", "Каналы", "Channels"),
      tag("telegram_bots", "🤖", "Боты", "Bots"),
      tag("telegram_ton", "💎", "TON", "TON"),
      tag("telegram_updates", "🆕", "Обновления", "Updates"),
      tag("telegram_other", "☝️", "Другое", "Other"),
    ],
  },
  {
    ...tag("creativity", "✨", "Творчество", "Creativity"),
    children: [
      tag("creativity_all", "✨", "Все", "All"),
      tag("creativity_handmade", "🪡", "Handmade", "Handmade"),
      tag("creativity_inspiration", "💡", "Вдохновение", "Inspiration"),
      tag("creativity_other", "☝️", "Другое", "Other"),
    ],
  },
  {
    ...tag("other", "☝️", "Другое", "Other"),
    children: [
      tag("other_all", "☝️", "Все", "All"),
      tag("other_misc", "📦", "Разное", "Misc"),
    ],
  },
];

const ALL_TAGS_MAP = new Map<string, SiteTag>();

for (const group of SITE_TAG_GROUPS) {
  ALL_TAGS_MAP.set(group.value, {
    value: group.value,
    emoji: group.emoji,
    labels: group.labels,
  });

  for (const child of group.children) {
    if (!ALL_TAGS_MAP.has(child.value)) {
      ALL_TAGS_MAP.set(child.value, child);
    }
  }
}

export const ALL_SITE_TAGS: SiteTag[] = Array.from(ALL_TAGS_MAP.values());
export const SITE_TAG_VALUES = ALL_SITE_TAGS.map((tag) => tag.value);

export function getTagLabel(tag: SiteTag, locale: SiteLocale) {
  return `${tag.emoji} ${tag.labels[locale] ?? tag.labels.us}`;
}

export function findTagByValue(value: string) {
  return ALL_TAGS_MAP.get(value);
}

export function findTagGroupByValue(value: string) {
  return SITE_TAG_GROUPS.find((group) => group.value === value);
}

export function findTagGroupByChildValue(value: string) {
  return SITE_TAG_GROUPS.find((group) =>
    group.children.some((child) => child.value === value)
  );
}

export function getTagChildren(parentValue: string) {
  return findTagGroupByValue(parentValue)?.children ?? [];
}

export function isParentTagValue(value: string) {
  return SITE_TAG_GROUPS.some((group) => group.value === value);
}

export function isChildTagValue(value: string) {
  return SITE_TAG_GROUPS.some((group) =>
    group.children.some((child) => child.value === value)
  );
}