import type { Locale } from "../../../types/app";

export type TrendsCopy = {
  all: string;
  back: string;
  loading: string;
  searchPlaceholder: string;
  clearSearch: string;
  more: string;
  hide: string;
  myTopics: string;
  interests: string;
  unsubscribeTopicTitle: string;
  discussingNow: string;
  today: string;
  mentions: string;
  sources: string;
  telegramAttention: string;
  now: string;
  followTopic: string;
  unfollowTopic: string;
  whyGrows: string;
  whyFalls: string;
  whyLineSources: string;
  whyLineActivityUp: string;
  whyLineActivityDown: string;
  whyLineRelated: string;
  whoFormsAttention: string;
  noSignals: string;
  fullAccess: string;
  follow: string;
  unsubscribe: string;
  explore: string;
};

const TRENDS_COPY: Record<Locale, TrendsCopy> = {
  ru: {
    all: "Все",
    back: "Назад",
    loading: "Загружаю сигналы Telegram...",
    searchPlaceholder: "Поиск по теме, бренду, событию...",
    clearSearch: "Очистить",
    more: "Ещё",
    hide: "Скрыть",
    myTopics: "Мои темы",
    interests: "Мои интересы",
    unsubscribeTopicTitle: "Отписаться от темы",
    discussingNow: "Что обсуждают сейчас",
    today: "сегодня",
    mentions: "упоминаний",
    sources: "источников",
    telegramAttention: "Telegram Attention",
    now: "сейчас",
    followTopic: "Следить за темой",
    unfollowTopic: "Отписаться от темы",
    whyGrows: "Почему тема растёт",
    whyFalls: "Почему тема угасает",
    whyLineSources: "тему одновременно подхватили {count} источников;",
    whyLineActivityUp: "последние публикации дают ускорение внимания;",
    whyLineActivityDown: "последние публикации дают затухание внимания;",
    whyLineRelated: "рядом с темой чаще всего встречаются: {chips}.",
    whoFormsAttention: "Кто формирует внимание",
    noSignals: "По этому запросу пока нет сигналов.",
    fullAccess: "🔓 Разблокировать все сигналы",
    follow: "Следить",
    unsubscribe: "✓ Отписаться",
    explore: "Исследовать",
  },
  ua: {
    all: "Усе",
    back: "Назад",
    loading: "Завантажую сигнали Telegram...",
    searchPlaceholder: "Пошук за темою, брендом, подією...",
    clearSearch: "Очистити",
    more: "Ще",
    hide: "Сховати",
    myTopics: "Мої теми",
    interests: "Мої інтереси",
    unsubscribeTopicTitle: "Відписатися від теми",
    discussingNow: "Що обговорюють зараз",
    today: "сьогодні",
    mentions: "згадок",
    sources: "джерел",
    telegramAttention: "Telegram Attention",
    now: "зараз",
    followTopic: "Стежити за темою",
    unfollowTopic: "Відписатися від теми",
    whyGrows: "Чому тема зростає",
    whyFalls: "Чому тема згасає",
    whyLineSources: "тему одночасно підхопили {count} джерел;",
    whyLineActivityUp: "останні публікації прискорюють увагу;",
    whyLineActivityDown: "останні публікації дають згасання уваги;",
    whyLineRelated: "поруч із темою найчастіше зустрічаються: {chips}.",
    whoFormsAttention: "Хто формує увагу",
    noSignals: "За цим запитом поки немає сигналів.",
    fullAccess: "🔓 Розблокувати всі сигнали",
    follow: "Стежити",
    unsubscribe: "✓ Відписатися",
    explore: "Дослідити",
  },
  us: {
    all: "All",
    back: "Back",
    loading: "Loading Telegram signals...",
    searchPlaceholder: "Search by topic, brand, event...",
    clearSearch: "Clear",
    more: "More",
    hide: "Hide",
    myTopics: "My topics",
    interests: "My interests",
    unsubscribeTopicTitle: "Unfollow topic",
    discussingNow: "What Telegram is discussing now",
    today: "today",
    mentions: "mentions",
    sources: "sources",
    telegramAttention: "Telegram Attention",
    now: "now",
    followTopic: "Follow this topic",
    unfollowTopic: "Unfollow this topic",
    whyGrows: "Why this topic is growing",
    whyFalls: "Why this topic is fading",
    whyLineSources: "the topic was picked up by {count} sources at once;",
    whyLineActivityUp: "latest posts are accelerating attention;",
    whyLineActivityDown: "latest posts are cooling attention down;",
    whyLineRelated: "most often appears near: {chips}.",
    whoFormsAttention: "Who shapes attention",
    noSignals: "No signals for this query yet.",
    fullAccess: "🔓 Unlock all signals",
    follow: "Follow",
    unsubscribe: "✓ Unfollow",
    explore: "Explore",
  },
  in: {
    all: "सभी",
    back: "वापस",
    loading: "Telegram संकेत लोड हो रहे हैं...",
    searchPlaceholder: "विषय, ब्रांड, घटना से खोजें...",
    clearSearch: "साफ़ करें",
    more: "और",
    hide: "छुपाएँ",
    myTopics: "मेरे विषय",
    interests: "मेरी रुचियाँ",
    unsubscribeTopicTitle: "विषय अनफॉलो करें",
    discussingNow: "अभी Telegram में क्या चर्चा है",
    today: "आज",
    mentions: "उल्लेख",
    sources: "स्रोत",
    telegramAttention: "Telegram Attention",
    now: "अभी",
    followTopic: "विषय को फॉलो करें",
    unfollowTopic: "विषय अनफॉलो करें",
    whyGrows: "यह विषय क्यों बढ़ रहा है",
    whyFalls: "यह विषय क्यों धीमा हो रहा है",
    whyLineSources: "इस विषय को एक साथ {count} स्रोतों ने उठाया;",
    whyLineActivityUp: "नए पोस्ट ध्यान को तेज़ कर रहे हैं;",
    whyLineActivityDown: "नए पोस्ट ध्यान को धीमा कर रहे हैं;",
    whyLineRelated: "इस विषय के साथ अक्सर दिखता है: {chips}.",
    whoFormsAttention: "ध्यान कौन बना रहा है",
    noSignals: "इस खोज के लिए अभी कोई संकेत नहीं.",
    fullAccess: "🔓 सभी संकेत अनलॉक करें",
    follow: "Follow",
    unsubscribe: "✓ Unfollow",
    explore: "Explore",
  },
  ir: {
    all: "همه",
    back: "بازگشت",
    loading: "در حال بارگذاری سیگنال‌های Telegram...",
    searchPlaceholder: "جستجو بر اساس موضوع، برند، رویداد...",
    clearSearch: "پاک کردن",
    more: "بیشتر",
    hide: "پنهان",
    myTopics: "موضوعات من",
    interests: "علاقه‌های من",
    unsubscribeTopicTitle: "لغو دنبال‌کردن موضوع",
    discussingNow: "اکنون در Telegram چه چیزی بحث می‌شود",
    today: "امروز",
    mentions: "اشاره",
    sources: "منبع",
    telegramAttention: "Telegram Attention",
    now: "اکنون",
    followTopic: "دنبال‌کردن موضوع",
    unfollowTopic: "لغو دنبال‌کردن موضوع",
    whyGrows: "چرا این موضوع رشد می‌کند",
    whyFalls: "چرا این موضوع افت می‌کند",
    whyLineSources: "این موضوع هم‌زمان توسط {count} منبع مطرح شد؛",
    whyLineActivityUp: "پست‌های جدید توجه را سرعت می‌دهند؛",
    whyLineActivityDown: "پست‌های جدید توجه را کم‌رنگ می‌کنند؛",
    whyLineRelated: "بیشتر کنار این موارد دیده می‌شود: {chips}.",
    whoFormsAttention: "چه کسی توجه را شکل می‌دهد",
    noSignals: "برای این جستجو هنوز سیگنالی نیست.",
    fullAccess: "🔓 باز کردن همه سیگنال‌ها",
    follow: "دنبال‌کردن",
    unsubscribe: "✓ لغو",
    explore: "بررسی",
  },
  tr: {
    all: "Tümü",
    back: "Geri",
    loading: "Telegram sinyalleri yükleniyor...",
    searchPlaceholder: "Konu, marka, olay ara...",
    clearSearch: "Temizle",
    more: "Daha",
    hide: "Gizle",
    myTopics: "Konularım",
    interests: "İlgi alanlarım",
    unsubscribeTopicTitle: "Konuyu takipten çıkar",
    discussingNow: "Telegram şu anda ne konuşuyor",
    today: "bugün",
    mentions: "bahsetme",
    sources: "kaynak",
    telegramAttention: "Telegram Attention",
    now: "şimdi",
    followTopic: "Konuyu takip et",
    unfollowTopic: "Konuyu takipten çıkar",
    whyGrows: "Konu neden büyüyor",
    whyFalls: "Konu neden sönüyor",
    whyLineSources: "konu aynı anda {count} kaynak tarafından yakalandı;",
    whyLineActivityUp: "son paylaşımlar dikkati hızlandırıyor;",
    whyLineActivityDown: "son paylaşımlar dikkati azaltıyor;",
    whyLineRelated: "en sık yanında görülenler: {chips}.",
    whoFormsAttention: "Dikkati kim oluşturuyor",
    noSignals: "Bu sorgu için henüz sinyal yok.",
    fullAccess: "🔓 Tüm sinyallerin kilidini aç",
    follow: "Takip et",
    unsubscribe: "✓ Bırak",
    explore: "İncele",
  },
  br: {
    all: "Todos",
    back: "Voltar",
    loading: "Carregando sinais do Telegram...",
    searchPlaceholder: "Buscar por tema, marca, evento...",
    clearSearch: "Limpar",
    more: "Mais",
    hide: "Ocultar",
    myTopics: "Meus temas",
    interests: "Meus interesses",
    unsubscribeTopicTitle: "Deixar de seguir tema",
    discussingNow: "O que o Telegram discute agora",
    today: "hoje",
    mentions: "menções",
    sources: "fontes",
    telegramAttention: "Telegram Attention",
    now: "agora",
    followTopic: "Seguir tema",
    unfollowTopic: "Deixar de seguir tema",
    whyGrows: "Por que o tema cresce",
    whyFalls: "Por que o tema esfria",
    whyLineSources: "o tema foi captado por {count} fontes ao mesmo tempo;",
    whyLineActivityUp: "as publicações recentes aceleram a atenção;",
    whyLineActivityDown: "as publicações recentes reduzem a atenção;",
    whyLineRelated: "aparece com mais frequência perto de: {chips}.",
    whoFormsAttention: "Quem forma a atenção",
    noSignals: "Ainda não há sinais para esta busca.",
    fullAccess: "🔓 Desbloquear todos os sinais",
    follow: "Seguir",
    unsubscribe: "✓ Deixar",
    explore: "Explorar",
  },
  kz: {
    all: "Барлығы",
    back: "Артқа",
    loading: "Telegram сигналдары жүктелуде...",
    searchPlaceholder: "Тақырып, бренд, оқиға бойынша іздеу...",
    clearSearch: "Тазарту",
    more: "Тағы",
    hide: "Жасыру",
    myTopics: "Менің тақырыптарым",
    interests: "Менің қызығушылықтарым",
    unsubscribeTopicTitle: "Тақырыптан бас тарту",
    discussingNow: "Telegram қазір нені талқылап жатыр",
    today: "бүгін",
    mentions: "аталым",
    sources: "дереккөз",
    telegramAttention: "Telegram Attention",
    now: "қазір",
    followTopic: "Тақырыпты бақылау",
    unfollowTopic: "Тақырыптан бас тарту",
    whyGrows: "Неге тақырып өсіп жатыр",
    whyFalls: "Неге тақырып бәсеңдеп жатыр",
    whyLineSources: "тақырыпты бір уақытта {count} дереккөз көтерді;",
    whyLineActivityUp: "соңғы жарияланымдар назарды күшейтеді;",
    whyLineActivityDown: "соңғы жарияланымдар назарды бәсеңдетеді;",
    whyLineRelated: "жиі бірге кездеседі: {chips}.",
    whoFormsAttention: "Назарды кім қалыптастырады",
    noSignals: "Бұл сұрау бойынша әзірге сигнал жоқ.",
    fullAccess: "🔓 Барлық сигналдарды ашу",
    follow: "Бақылау",
    unsubscribe: "✓ Бас тарту",
    explore: "Зерттеу",
  },
  uz: {
    all: "Hammasi",
    back: "Orqaga",
    loading: "Telegram signallari yuklanmoqda...",
    searchPlaceholder: "Mavzu, brend, voqea bo‘yicha qidirish...",
    clearSearch: "Tozalash",
    more: "Yana",
    hide: "Yashirish",
    myTopics: "Mavzularim",
    interests: "Qiziqishlarim",
    unsubscribeTopicTitle: "Mavzudan chiqish",
    discussingNow: "Telegram hozir nimani muhokama qilmoqda",
    today: "bugun",
    mentions: "eslatma",
    sources: "manba",
    telegramAttention: "Telegram Attention",
    now: "hozir",
    followTopic: "Mavzuni kuzatish",
    unfollowTopic: "Mavzudan chiqish",
    whyGrows: "Nega mavzu o‘smoqda",
    whyFalls: "Nega mavzu pasaymoqda",
    whyLineSources: "mavzuni bir vaqtda {count} manba ko‘tardi;",
    whyLineActivityUp: "so‘nggi postlar e’tiborni tezlatmoqda;",
    whyLineActivityDown: "so‘nggi postlar e’tiborni pasaytirmoqda;",
    whyLineRelated: "ko‘pincha yonida uchraydi: {chips}.",
    whoFormsAttention: "E’tiborni kim shakllantiradi",
    noSignals: "Bu so‘rov bo‘yicha hozircha signal yo‘q.",
    fullAccess: "🔓 Barcha signallarni ochish",
    follow: "Kuzatish",
    unsubscribe: "✓ Chiqish",
    explore: "O‘rganish",
  },
  ae: {
    all: "الكل",
    back: "رجوع",
    loading: "جارٍ تحميل إشارات Telegram...",
    searchPlaceholder: "ابحث عن موضوع أو علامة أو حدث...",
    clearSearch: "مسح",
    more: "المزيد",
    hide: "إخفاء",
    myTopics: "مواضيعي",
    interests: "اهتماماتي",
    unsubscribeTopicTitle: "إلغاء متابعة الموضوع",
    discussingNow: "ما الذي يناقشه Telegram الآن",
    today: "اليوم",
    mentions: "ذكر",
    sources: "مصدر",
    telegramAttention: "Telegram Attention",
    now: "الآن",
    followTopic: "متابعة الموضوع",
    unfollowTopic: "إلغاء متابعة الموضوع",
    whyGrows: "لماذا ينمو الموضوع",
    whyFalls: "لماذا يخفت الموضوع",
    whyLineSources: "التقط {count} مصدرًا الموضوع في الوقت نفسه؛",
    whyLineActivityUp: "المنشورات الأخيرة تسرّع الانتباه؛",
    whyLineActivityDown: "المنشورات الأخيرة تخفّض الانتباه؛",
    whyLineRelated: "يظهر غالبًا بجانب: {chips}.",
    whoFormsAttention: "من يصنع الانتباه",
    noSignals: "لا توجد إشارات لهذا البحث بعد.",
    fullAccess: "🔓 فتح كل الإشارات",
    follow: "متابعة",
    unsubscribe: "✓ إلغاء",
    explore: "استكشاف",
  },
  eg: {
    all: "الكل",
    back: "رجوع",
    loading: "بنحمّل إشارات Telegram...",
    searchPlaceholder: "دور على موضوع أو براند أو حدث...",
    clearSearch: "مسح",
    more: "المزيد",
    hide: "إخفاء",
    myTopics: "مواضيعي",
    interests: "اهتماماتي",
    unsubscribeTopicTitle: "إلغاء متابعة الموضوع",
    discussingNow: "إيه اللي بيتناقش على Telegram دلوقتي",
    today: "النهارده",
    mentions: "ذكر",
    sources: "مصدر",
    telegramAttention: "Telegram Attention",
    now: "دلوقتي",
    followTopic: "تابع الموضوع",
    unfollowTopic: "إلغاء متابعة الموضوع",
    whyGrows: "ليه الموضوع بيكبر",
    whyFalls: "ليه الموضوع بيهدأ",
    whyLineSources: "الموضوع اتلقط من {count} مصدر في نفس الوقت؛",
    whyLineActivityUp: "آخر المنشورات بتسرّع الانتباه؛",
    whyLineActivityDown: "آخر المنشورات بتقلل الانتباه؛",
    whyLineRelated: "غالبًا بيظهر مع: {chips}.",
    whoFormsAttention: "مين بيشكّل الانتباه",
    noSignals: "مفيش إشارات للبحث ده لسه.",
    fullAccess: "🔓 افتح كل الإشارات",
    follow: "متابعة",
    unsubscribe: "✓ إلغاء",
    explore: "استكشاف",
  },
  pk: {
    all: "سب",
    back: "واپس",
    loading: "Telegram سگنلز لوڈ ہو رہے ہیں...",
    searchPlaceholder: "موضوع، برانڈ، واقعہ تلاش کریں...",
    clearSearch: "صاف کریں",
    more: "مزید",
    hide: "چھپائیں",
    myTopics: "میرے موضوعات",
    interests: "میری دلچسپیاں",
    unsubscribeTopicTitle: "موضوع اَن فالو کریں",
    discussingNow: "Telegram پر ابھی کیا بحث ہو رہی ہے",
    today: "آج",
    mentions: "ذکر",
    sources: "ذرائع",
    telegramAttention: "Telegram Attention",
    now: "ابھی",
    followTopic: "موضوع فالو کریں",
    unfollowTopic: "موضوع اَن فالو کریں",
    whyGrows: "موضوع کیوں بڑھ رہا ہے",
    whyFalls: "موضوع کیوں کم ہو رہا ہے",
    whyLineSources: "اس موضوع کو ایک ساتھ {count} ذرائع نے اٹھایا؛",
    whyLineActivityUp: "نئی پوسٹس توجہ تیز کر رہی ہیں؛",
    whyLineActivityDown: "نئی پوسٹس توجہ کم کر رہی ہیں؛",
    whyLineRelated: "اکثر ساتھ آتا ہے: {chips}.",
    whoFormsAttention: "توجہ کون بنا رہا ہے",
    noSignals: "اس تلاش کے لیے ابھی کوئی سگنل نہیں.",
    fullAccess: "🔓 تمام سگنلز کھولیں",
    follow: "فالو",
    unsubscribe: "✓ اَن فالو",
    explore: "دیکھیں",
  },
  id: {
    all: "Semua",
    back: "Kembali",
    loading: "Memuat sinyal Telegram...",
    searchPlaceholder: "Cari topik, brand, peristiwa...",
    clearSearch: "Hapus",
    more: "Lainnya",
    hide: "Sembunyikan",
    myTopics: "Topik saya",
    interests: "Minat saya",
    unsubscribeTopicTitle: "Berhenti mengikuti topik",
    discussingNow: "Apa yang dibahas Telegram sekarang",
    today: "hari ini",
    mentions: "sebutan",
    sources: "sumber",
    telegramAttention: "Telegram Attention",
    now: "sekarang",
    followTopic: "Ikuti topik",
    unfollowTopic: "Berhenti mengikuti topik",
    whyGrows: "Mengapa topik naik",
    whyFalls: "Mengapa topik mereda",
    whyLineSources: "topik ini diangkat oleh {count} sumber sekaligus;",
    whyLineActivityUp: "posting terbaru mempercepat perhatian;",
    whyLineActivityDown: "posting terbaru menurunkan perhatian;",
    whyLineRelated: "paling sering muncul bersama: {chips}.",
    whoFormsAttention: "Siapa yang membentuk perhatian",
    noSignals: "Belum ada sinyal untuk pencarian ini.",
    fullAccess: "🔓 Buka semua sinyal",
    follow: "Ikuti",
    unsubscribe: "✓ Berhenti",
    explore: "Jelajahi",
  },
  mx: {
    all: "Todo",
    back: "Atrás",
    loading: "Cargando señales de Telegram...",
    searchPlaceholder: "Busca tema, marca, evento...",
    clearSearch: "Limpiar",
    more: "Más",
    hide: "Ocultar",
    myTopics: "Mis temas",
    interests: "Mis intereses",
    unsubscribeTopicTitle: "Dejar de seguir tema",
    discussingNow: "Qué se habla ahora en Telegram",
    today: "hoy",
    mentions: "menciones",
    sources: "fuentes",
    telegramAttention: "Telegram Attention",
    now: "ahora",
    followTopic: "Seguir tema",
    unfollowTopic: "Dejar de seguir tema",
    whyGrows: "Por qué crece el tema",
    whyFalls: "Por qué se apaga el tema",
    whyLineSources: "el tema fue tomado por {count} fuentes a la vez;",
    whyLineActivityUp: "las publicaciones recientes aceleran la atención;",
    whyLineActivityDown: "las publicaciones recientes reducen la atención;",
    whyLineRelated: "aparece con más frecuencia junto a: {chips}.",
    whoFormsAttention: "Quién forma la atención",
    noSignals: "Todavía no hay señales para esta búsqueda.",
    fullAccess: "🔓 Desbloquear todas las señales",
    follow: "Seguir",
    unsubscribe: "✓ Dejar",
    explore: "Explorar",
  },
  sa: {
    all: "الكل",
    back: "رجوع",
    loading: "جارٍ تحميل إشارات Telegram...",
    searchPlaceholder: "ابحث عن موضوع أو علامة أو حدث...",
    clearSearch: "مسح",
    more: "المزيد",
    hide: "إخفاء",
    myTopics: "مواضيعي",
    interests: "اهتماماتي",
    unsubscribeTopicTitle: "إلغاء متابعة الموضوع",
    discussingNow: "ما الذي يناقشه Telegram الآن",
    today: "اليوم",
    mentions: "ذكر",
    sources: "مصدر",
    telegramAttention: "Telegram Attention",
    now: "الآن",
    followTopic: "متابعة الموضوع",
    unfollowTopic: "إلغاء متابعة الموضوع",
    whyGrows: "لماذا ينمو الموضوع",
    whyFalls: "لماذا يخفت الموضوع",
    whyLineSources: "التقط {count} مصدرًا الموضوع في الوقت نفسه؛",
    whyLineActivityUp: "المنشورات الأخيرة تسرّع الانتباه؛",
    whyLineActivityDown: "المنشورات الأخيرة تخفّض الانتباه؛",
    whyLineRelated: "يظهر غالبًا بجانب: {chips}.",
    whoFormsAttention: "من يصنع الانتباه",
    noSignals: "لا توجد إشارات لهذا البحث بعد.",
    fullAccess: "🔓 فتح كل الإشارات",
    follow: "متابعة",
    unsubscribe: "✓ إلغاء",
    explore: "استكشاف",
  },
  es: {
    all: "Todo",
    back: "Atrás",
    loading: "Cargando señales de Telegram...",
    searchPlaceholder: "Busca por tema, marca, evento...",
    clearSearch: "Limpiar",
    more: "Más",
    hide: "Ocultar",
    myTopics: "Mis temas",
    interests: "Mis intereses",
    unsubscribeTopicTitle: "Dejar de seguir tema",
    discussingNow: "Qué se está hablando en Telegram",
    today: "hoy",
    mentions: "menciones",
    sources: "fuentes",
    telegramAttention: "Telegram Attention",
    now: "ahora",
    followTopic: "Seguir tema",
    unfollowTopic: "Dejar de seguir tema",
    whyGrows: "Por qué crece el tema",
    whyFalls: "Por qué se apaga el tema",
    whyLineSources: "el tema fue recogido por {count} fuentes a la vez;",
    whyLineActivityUp: "las publicaciones recientes aceleran la atención;",
    whyLineActivityDown: "las publicaciones recientes enfrían la atención;",
    whyLineRelated: "aparece con más frecuencia junto a: {chips}.",
    whoFormsAttention: "Quién forma la atención",
    noSignals: "Aún no hay señales para esta búsqueda.",
    fullAccess: "🔓 Desbloquear todas las señales",
    follow: "Seguir",
    unsubscribe: "✓ Dejar",
    explore: "Explorar",
  },
  it: {
    all: "Tutto",
    back: "Indietro",
    loading: "Caricamento segnali Telegram...",
    searchPlaceholder: "Cerca per tema, brand, evento...",
    clearSearch: "Cancella",
    more: "Altro",
    hide: "Nascondi",
    myTopics: "I miei temi",
    interests: "I miei interessi",
    unsubscribeTopicTitle: "Smetti di seguire il tema",
    discussingNow: "Cosa si discute ora su Telegram",
    today: "oggi",
    mentions: "menzioni",
    sources: "fonti",
    telegramAttention: "Telegram Attention",
    now: "ora",
    followTopic: "Segui il tema",
    unfollowTopic: "Smetti di seguire il tema",
    whyGrows: "Perché il tema cresce",
    whyFalls: "Perché il tema cala",
    whyLineSources: "il tema è stato ripreso da {count} fonti insieme;",
    whyLineActivityUp: "gli ultimi post accelerano l’attenzione;",
    whyLineActivityDown: "gli ultimi post raffreddano l’attenzione;",
    whyLineRelated: "appare più spesso vicino a: {chips}.",
    whoFormsAttention: "Chi forma l’attenzione",
    noSignals: "Non ci sono ancora segnali per questa ricerca.",
    fullAccess: "🔓 Sblocca tutti i segnali",
    follow: "Segui",
    unsubscribe: "✓ Smetti",
    explore: "Esplora",
  },
  fr: {
    all: "Tout",
    back: "Retour",
    loading: "Chargement des signaux Telegram...",
    searchPlaceholder: "Rechercher un sujet, une marque, un événement...",
    clearSearch: "Effacer",
    more: "Plus",
    hide: "Masquer",
    myTopics: "Mes sujets",
    interests: "Mes intérêts",
    unsubscribeTopicTitle: "Ne plus suivre le sujet",
    discussingNow: "Ce que Telegram discute maintenant",
    today: "aujourd’hui",
    mentions: "mentions",
    sources: "sources",
    telegramAttention: "Telegram Attention",
    now: "maintenant",
    followTopic: "Suivre le sujet",
    unfollowTopic: "Ne plus suivre le sujet",
    whyGrows: "Pourquoi le sujet monte",
    whyFalls: "Pourquoi le sujet faiblit",
    whyLineSources: "le sujet a été repris par {count} sources à la fois ;",
    whyLineActivityUp: "les dernières publications accélèrent l’attention ;",
    whyLineActivityDown:
      "les dernières publications refroidissent l’attention ;",
    whyLineRelated: "apparaît le plus souvent avec : {chips}.",
    whoFormsAttention: "Qui forme l’attention",
    noSignals: "Aucun signal pour cette recherche pour le moment.",
    fullAccess: "🔓 Débloquer tous les signaux",
    follow: "Suivre",
    unsubscribe: "✓ Arrêter",
    explore: "Explorer",
  },
  de: {
    all: "Alle",
    back: "Zurück",
    loading: "Telegram-Signale werden geladen...",
    searchPlaceholder: "Nach Thema, Marke, Ereignis suchen...",
    clearSearch: "Löschen",
    more: "Mehr",
    hide: "Ausblenden",
    myTopics: "Meine Themen",
    interests: "Meine Interessen",
    unsubscribeTopicTitle: "Thema nicht mehr verfolgen",
    discussingNow: "Was Telegram gerade diskutiert",
    today: "heute",
    mentions: "Erwähnungen",
    sources: "Quellen",
    telegramAttention: "Telegram Attention",
    now: "jetzt",
    followTopic: "Thema verfolgen",
    unfollowTopic: "Thema nicht mehr verfolgen",
    whyGrows: "Warum das Thema wächst",
    whyFalls: "Warum das Thema abkühlt",
    whyLineSources:
      "das Thema wurde gleichzeitig von {count} Quellen aufgegriffen;",
    whyLineActivityUp: "neue Beiträge beschleunigen die Aufmerksamkeit;",
    whyLineActivityDown: "neue Beiträge lassen die Aufmerksamkeit abklingen;",
    whyLineRelated: "erscheint am häufigsten neben: {chips}.",
    whoFormsAttention: "Wer Aufmerksamkeit formt",
    noSignals: "Für diese Suche gibt es noch keine Signale.",
    fullAccess: "🔓 Alle Signale freischalten",
    follow: "Folgen",
    unsubscribe: "✓ Entfolgen",
    explore: "Erkunden",
  },
  ar: {
    all: "Todo",
    back: "Atrás",
    loading: "Cargando señales de Telegram...",
    searchPlaceholder: "Buscar tema, marca, evento...",
    clearSearch: "Limpiar",
    more: "Más",
    hide: "Ocultar",
    myTopics: "Mis temas",
    interests: "Mis intereses",
    unsubscribeTopicTitle: "Dejar de seguir tema",
    discussingNow: "Qué se habla ahora en Telegram",
    today: "hoy",
    mentions: "menciones",
    sources: "fuentes",
    telegramAttention: "Telegram Attention",
    now: "ahora",
    followTopic: "Seguir tema",
    unfollowTopic: "Dejar de seguir tema",
    whyGrows: "Por qué crece el tema",
    whyFalls: "Por qué se apaga el tema",
    whyLineSources: "el tema fue tomado por {count} fuentes a la vez;",
    whyLineActivityUp: "las publicaciones recientes aceleran la atención;",
    whyLineActivityDown: "las publicaciones recientes reducen la atención;",
    whyLineRelated: "aparece con más frecuencia junto a: {chips}.",
    whoFormsAttention: "Quién forma la atención",
    noSignals: "Todavía no hay señales para esta búsqueda.",
    fullAccess: "🔓 Desbloquear todas las señales",
    follow: "Seguir",
    unsubscribe: "✓ Dejar",
    explore: "Explorar",
  },
  co: {
    all: "Todo",
    back: "Atrás",
    loading: "Cargando señales de Telegram...",
    searchPlaceholder: "Busca tema, marca, evento...",
    clearSearch: "Limpiar",
    more: "Más",
    hide: "Ocultar",
    myTopics: "Mis temas",
    interests: "Mis intereses",
    unsubscribeTopicTitle: "Dejar de seguir tema",
    discussingNow: "Qué se habla ahora en Telegram",
    today: "hoy",
    mentions: "menciones",
    sources: "fuentes",
    telegramAttention: "Telegram Attention",
    now: "ahora",
    followTopic: "Seguir tema",
    unfollowTopic: "Dejar de seguir tema",
    whyGrows: "Por qué crece el tema",
    whyFalls: "Por qué se apaga el tema",
    whyLineSources: "el tema fue tomado por {count} fuentes a la vez;",
    whyLineActivityUp: "las publicaciones recientes aceleran la atención;",
    whyLineActivityDown: "las publicaciones recientes reducen la atención;",
    whyLineRelated: "aparece con más frecuencia junto a: {chips}.",
    whoFormsAttention: "Quién forma la atención",
    noSignals: "Todavía no hay señales para esta búsqueda.",
    fullAccess: "🔓 Desbloquear todas las señales",
    follow: "Seguir",
    unsubscribe: "✓ Dejar",
    explore: "Explorar",
  },
  za: {
    all: "All",
    back: "Back",
    loading: "Loading Telegram signals...",
    searchPlaceholder: "Search by topic, brand, event...",
    clearSearch: "Clear",
    more: "More",
    hide: "Hide",
    myTopics: "My topics",
    interests: "My interests",
    unsubscribeTopicTitle: "Unfollow topic",
    discussingNow: "What Telegram is discussing now",
    today: "today",
    mentions: "mentions",
    sources: "sources",
    telegramAttention: "Telegram Attention",
    now: "now",
    followTopic: "Follow this topic",
    unfollowTopic: "Unfollow this topic",
    whyGrows: "Why this topic is growing",
    whyFalls: "Why this topic is fading",
    whyLineSources: "the topic was picked up by {count} sources at once;",
    whyLineActivityUp: "latest posts are accelerating attention;",
    whyLineActivityDown: "latest posts are cooling attention down;",
    whyLineRelated: "most often appears near: {chips}.",
    whoFormsAttention: "Who shapes attention",
    noSignals: "No signals for this query yet.",
    fullAccess: "🔓 Unlock all signals",
    follow: "Follow",
    unsubscribe: "✓ Unfollow",
    explore: "Explore",
  },
  ng: {
    all: "All",
    back: "Back",
    loading: "Loading Telegram signals...",
    searchPlaceholder: "Search by topic, brand, event...",
    clearSearch: "Clear",
    more: "More",
    hide: "Hide",
    myTopics: "My topics",
    interests: "My interests",
    unsubscribeTopicTitle: "Unfollow topic",
    discussingNow: "What Telegram is discussing now",
    today: "today",
    mentions: "mentions",
    sources: "sources",
    telegramAttention: "Telegram Attention",
    now: "now",
    followTopic: "Follow this topic",
    unfollowTopic: "Unfollow this topic",
    whyGrows: "Why this topic is growing",
    whyFalls: "Why this topic is fading",
    whyLineSources: "the topic was picked up by {count} sources at once;",
    whyLineActivityUp: "latest posts are accelerating attention;",
    whyLineActivityDown: "latest posts are cooling attention down;",
    whyLineRelated: "most often appears near: {chips}.",
    whoFormsAttention: "Who shapes attention",
    noSignals: "No signals for this query yet.",
    fullAccess: "🔓 Unlock all signals",
    follow: "Follow",
    unsubscribe: "✓ Unfollow",
    explore: "Explore",
  },
  cn: {
    all: "全部",
    back: "返回",
    loading: "正在加载 Telegram 信号...",
    searchPlaceholder: "按主题、品牌、事件搜索...",
    clearSearch: "清除",
    more: "更多",
    hide: "收起",
    myTopics: "我的主题",
    interests: "我的兴趣",
    unsubscribeTopicTitle: "取消关注主题",
    discussingNow: "Telegram 正在讨论什么",
    today: "今天",
    mentions: "提及",
    sources: "来源",
    telegramAttention: "Telegram Attention",
    now: "现在",
    followTopic: "关注主题",
    unfollowTopic: "取消关注主题",
    whyGrows: "为什么这个主题在增长",
    whyFalls: "为什么这个主题在减弱",
    whyLineSources: "该主题同时被 {count} 个来源提及；",
    whyLineActivityUp: "最新发布正在加速关注；",
    whyLineActivityDown: "最新发布正在降低关注；",
    whyLineRelated: "最常一起出现：{chips}.",
    whoFormsAttention: "谁在形成关注",
    noSignals: "此搜索暂时没有信号。",
    fullAccess: "🔓 解锁全部信号",
    follow: "关注",
    unsubscribe: "✓ 取消",
    explore: "探索",
  },
  my: {
    all: "Semua",
    back: "Kembali",
    loading: "Memuatkan isyarat Telegram...",
    searchPlaceholder: "Cari topik, jenama, acara...",
    clearSearch: "Kosongkan",
    more: "Lagi",
    hide: "Sembunyi",
    myTopics: "Topik saya",
    interests: "Minat saya",
    unsubscribeTopicTitle: "Berhenti ikut topik",
    discussingNow: "Apa yang dibincangkan di Telegram sekarang",
    today: "hari ini",
    mentions: "sebutan",
    sources: "sumber",
    telegramAttention: "Telegram Attention",
    now: "sekarang",
    followTopic: "Ikut topik",
    unfollowTopic: "Berhenti ikut topik",
    whyGrows: "Mengapa topik ini naik",
    whyFalls: "Mengapa topik ini reda",
    whyLineSources: "topik ini diangkat oleh {count} sumber serentak;",
    whyLineActivityUp: "siaran terkini mempercepat perhatian;",
    whyLineActivityDown: "siaran terkini meredakan perhatian;",
    whyLineRelated: "paling kerap muncul bersama: {chips}.",
    whoFormsAttention: "Siapa membentuk perhatian",
    noSignals: "Belum ada isyarat untuk carian ini.",
    fullAccess: "🔓 Buka semua isyarat",
    follow: "Ikut",
    unsubscribe: "✓ Berhenti",
    explore: "Teroka",
  },
};

export function getTrendsCopy(locale: Locale) {
  return TRENDS_COPY[locale] || TRENDS_COPY.us;
}

type TrendsExtraCopy = {
  shownSources: string;
  showMoreSources: string;
  unlockAllSignals: string;
  fullReport24h: string;
};

const TRENDS_EXTRA_COPY: Record<Locale, TrendsExtraCopy> = {
  ru: {
    shownSources: "Показано {shown} из {total} {sources}",
    showMoreSources: "Показать ещё 10",
    unlockAllSignals: "🔓 Разблокировать все сигналы",
    fullReport24h: "Полный отчёт за 24 часа",
  },
  ua: {
    shownSources: "Показано {shown} з {total} {sources}",
    showMoreSources: "Показати ще 10",
    unlockAllSignals: "🔓 Розблокувати всі сигнали",
    fullReport24h: "Повний звіт за 24 години",
  },
  us: {
    shownSources: "Showing {shown} of {total} {sources}",
    showMoreSources: "Show 10 more",
    unlockAllSignals: "🔓 Unlock all signals",
    fullReport24h: "Full 24-hour report",
  },
  in: {
    shownSources: "{total} {sources} में से {shown} दिखाए गए",
    showMoreSources: "10 और दिखाएँ",
    unlockAllSignals: "🔓 सभी संकेत अनलॉक करें",
    fullReport24h: "24 घंटे की पूरी रिपोर्ट",
  },
  ir: {
    shownSources: "نمایش {shown} از {total} {sources}",
    showMoreSources: "نمایش ۱۰ مورد دیگر",
    unlockAllSignals: "🔓 باز کردن همه سیگنال‌ها",
    fullReport24h: "گزارش کامل ۲۴ ساعت",
  },
  tr: {
    shownSources: "{total} {sources} içinden {shown} gösteriliyor",
    showMoreSources: "10 tane daha göster",
    unlockAllSignals: "🔓 Tüm sinyallerin kilidini aç",
    fullReport24h: "24 saatlik tam rapor",
  },
  br: {
    shownSources: "Mostrando {shown} de {total} {sources}",
    showMoreSources: "Mostrar mais 10",
    unlockAllSignals: "🔓 Desbloquear todos os sinais",
    fullReport24h: "Relatório completo de 24 horas",
  },
  kz: {
    shownSources: "{total} {sources} ішінен {shown} көрсетілді",
    showMoreSources: "Тағы 10 көрсету",
    unlockAllSignals: "🔓 Барлық сигналдарды ашу",
    fullReport24h: "24 сағаттық толық есеп",
  },
  uz: {
    shownSources: "{total} {sources} ichidan {shown} ko‘rsatildi",
    showMoreSources: "Yana 10 ta ko‘rsatish",
    unlockAllSignals: "🔓 Barcha signallarni ochish",
    fullReport24h: "24 soatlik to‘liq hisobot",
  },
  ae: {
    shownSources: "عرض {shown} من {total} {sources}",
    showMoreSources: "عرض 10 أخرى",
    unlockAllSignals: "🔓 فتح كل الإشارات",
    fullReport24h: "تقرير كامل خلال 24 ساعة",
  },
  eg: {
    shownSources: "عرض {shown} من {total} {sources}",
    showMoreSources: "عرض 10 كمان",
    unlockAllSignals: "🔓 افتح كل الإشارات",
    fullReport24h: "تقرير كامل خلال 24 ساعة",
  },
  pk: {
    shownSources: "{total} {sources} میں سے {shown} دکھائے گئے",
    showMoreSources: "مزید 10 دکھائیں",
    unlockAllSignals: "🔓 تمام سگنلز کھولیں",
    fullReport24h: "24 گھنٹے کی مکمل رپورٹ",
  },
  id: {
    shownSources: "Menampilkan {shown} dari {total} {sources}",
    showMoreSources: "Tampilkan 10 lagi",
    unlockAllSignals: "🔓 Buka semua sinyal",
    fullReport24h: "Laporan penuh 24 jam",
  },
  mx: {
    shownSources: "Mostrando {shown} de {total} {sources}",
    showMoreSources: "Mostrar 10 más",
    unlockAllSignals: "🔓 Desbloquear todas las señales",
    fullReport24h: "Reporte completo de 24 horas",
  },
  sa: {
    shownSources: "عرض {shown} من {total} {sources}",
    showMoreSources: "عرض 10 أخرى",
    unlockAllSignals: "🔓 فتح كل الإشارات",
    fullReport24h: "تقرير كامل خلال 24 ساعة",
  },
  es: {
    shownSources: "Mostrando {shown} de {total} {sources}",
    showMoreSources: "Mostrar 10 más",
    unlockAllSignals: "🔓 Desbloquear todas las señales",
    fullReport24h: "Informe completo de 24 horas",
  },
  it: {
    shownSources: "Mostrati {shown} di {total} {sources}",
    showMoreSources: "Mostra altri 10",
    unlockAllSignals: "🔓 Sblocca tutti i segnali",
    fullReport24h: "Report completo di 24 ore",
  },
  fr: {
    shownSources: "{shown} sur {total} {sources} affichés",
    showMoreSources: "Afficher 10 de plus",
    unlockAllSignals: "🔓 Débloquer tous les signaux",
    fullReport24h: "Rapport complet sur 24 h",
  },
  de: {
    shownSources: "{shown} von {total} {sources} angezeigt",
    showMoreSources: "10 weitere anzeigen",
    unlockAllSignals: "🔓 Alle Signale freischalten",
    fullReport24h: "Vollständiger 24-Stunden-Bericht",
  },
  ar: {
    shownSources: "Mostrando {shown} de {total} {sources}",
    showMoreSources: "Mostrar 10 más",
    unlockAllSignals: "🔓 Desbloquear todas las señales",
    fullReport24h: "Reporte completo de 24 horas",
  },
  co: {
    shownSources: "Mostrando {shown} de {total} {sources}",
    showMoreSources: "Mostrar 10 más",
    unlockAllSignals: "🔓 Desbloquear todas las señales",
    fullReport24h: "Reporte completo de 24 horas",
  },
  za: {
    shownSources: "Showing {shown} of {total} {sources}",
    showMoreSources: "Show 10 more",
    unlockAllSignals: "🔓 Unlock all signals",
    fullReport24h: "Full 24-hour report",
  },
  ng: {
    shownSources: "Showing {shown} of {total} {sources}",
    showMoreSources: "Show 10 more",
    unlockAllSignals: "🔓 Unlock all signals",
    fullReport24h: "Full 24-hour report",
  },
  cn: {
    shownSources: "已显示 {shown} / {total} 个{sources}",
    showMoreSources: "再显示 10 个",
    unlockAllSignals: "🔓 解锁全部信号",
    fullReport24h: "查看 24 小时完整报告",
  },
  my: {
    shownSources: "Memaparkan {shown} daripada {total} {sources}",
    showMoreSources: "Papar 10 lagi",
    unlockAllSignals: "🔓 Buka semua isyarat",
    fullReport24h: "Laporan penuh 24 jam",
  },
};

export function getTrendsExtraCopy(locale: Locale) {
  return TRENDS_EXTRA_COPY[locale] || TRENDS_EXTRA_COPY.us;
}
