export const publicAuthors = [
  {
    id: "jim",
    name: "Jim Carter",
    handle: "@jimcreator",
    image: "",
    bio: "Создаёт практичных контент-агентов для роста, shorts и faceless публикации.",
    installs: "24.7k",
    revenue: "⭐ 8,420",
  },
  {
    id: "anna",
    name: "Anna Volkov",
    handle: "@annalabs",
    image: "",
    bio: "Делает быстрые новостные форматы и системы контента с высокой удерживаемостью.",
    installs: "13.2k",
    revenue: "⭐ 4,900",
  },
  {
    id: "leo",
    name: "Leo Stone",
    handle: "@leostudio",
    image: "",
    bio: "Создаёт faceless-движки для бизнес-контента и фактов.",
    installs: "9.8k",
    revenue: "⭐ 3,600",
  },
];

export const publicTemplateLibrary = [
  {
    id: "motivation",
    icon: "🔥",
    key: "motivation",
    topic: "motivation",
    videos: 5,
    length: 30,
    style: "Hook + advice",
    autopost: false,
    authorId: "jim",
  },
  {
    id: "news",
    icon: "📰",
    key: "news",
    topic: "news",
    videos: 12,
    length: 45,
    style: "Fast update",
    autopost: true,
    authorId: "anna",
  },
  {
    id: "facts",
    icon: "🧠",
    key: "facts",
    topic: "facts",
    videos: 8,
    length: 20,
    style: "Voice + captions",
    autopost: false,
    authorId: "leo",
  },
  {
    id: "business",
    icon: "💼",
    key: "business",
    topic: "business",
    videos: 3,
    length: 60,
    style: "Talking head / AI voice",
    autopost: true,
    authorId: "leo",
  },
];

export const publicAgents = [
  {
    id: 1,
    name: "Motivation Agent",
    topic: "мотивация",
    videos: 5,
    active: true,
    status: "In work",
    platform: "TikTok + Shorts",
    lastRun: "2 min ago",
    health: "healthy",
    autopost: false,
    mode: "Manual",
    length: 30,
    voice: "AI voice",
    style: "Hook + script + captions",
  },
  {
    id: 2,
    name: "Business Agent",
    topic: "бизнес",
    videos: 3,
    active: false,
    status: "Paused",
    platform: "Telegram",
    lastRun: "1 hour ago",
    health: "warning",
    autopost: false,
    mode: "Manual",
    length: 60,
    voice: "Cloned voice",
    style: "Talking head assistant",
  },
  {
    id: 3,
    name: "News Agent",
    topic: "новости",
    videos: 12,
    active: true,
    status: "In work",
    platform: "Reels + Telegram",
    lastRun: "just now",
    health: "healthy",
    autopost: true,
    mode: "Auto",
    length: 45,
    voice: "AI voice",
    style: "News recap",
  },
];

export const publicFeedItems = [
  {
    id: 1,
    authorId: "anna",
    growth: "+38%",
    labelEn: "AI News Shorts",
    labelRu: "AI Новости",
    titleEn: "AI just replaced another job category this week",
    titleRu: "AI уже заменил ещё одну категорию профессий на этой неделе",
    captionEn:
      "Fast hook, quick context, why it matters and a CTA to install the agent.",
    captionRu:
      "Быстрый хук, контекст, почему это важно и CTA на установку агента.",
    views: "1.2M",
    installs: "2.4k",
    agent: "News Agent",
  },
  {
    id: 2,
    authorId: "jim",
    growth: "+24%",
    labelEn: "Motivation Viral",
    labelRu: "Вирусная мотивация",
    titleEn: "Nobody tells you this about discipline and momentum",
    titleRu: "Никто не говорит тебе этого о дисциплине и инерции",
    captionEn:
      "Classic faceless motivational format with bold captions and dark stock visuals.",
    captionRu:
      "Классический faceless-мотивационный формат с жирными субтитрами и тёмным стоком.",
    views: "846k",
    installs: "1.1k",
    agent: "Motivation Agent",
  },
  {
    id: 3,
    authorId: "leo",
    growth: "+17%",
    labelEn: "History Facts",
    labelRu: "Исторические факты",
    titleEn: "This event quietly changed the direction of the world",
    titleRu: "Это событие тихо изменило направление мира",
    captionEn:
      "Curiosity-driven history short designed to pull installs from viewers into the store.",
    captionRu:
      "Формат на любопытстве, который переводит зрителей из видео в установку агента.",
    views: "604k",
    installs: "730",
    agent: "Facts Agent",
  },
];